/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

// THIS FILE WAS GENERATED BY scripts/generate-cics-keyword-tokens.mts
// DO NOT EDIT THIS FILE DIRECTLY. INSTEAD, EDIT THE GENERATOR AND RE-GENERATE THE FILE.

import { registerKeyword, KeywordType } from "./shared";

export const ABCODE = registerKeyword({
  name: "ABCODE",
});
export const ABDUMP = registerKeyword({
  name: "ABDUMP",
});
export const ABEND = registerKeyword({
  name: "ABEND",
  type: KeywordType.Control,
});
export const ABOFFSET = registerKeyword({
  name: "ABOFFSET",
});
export const ABORT = registerKeyword({
  name: "ABORT",
  type: KeywordType.Control,
});
export const ABPROGRAM = registerKeyword({
  name: "ABPROGRAM",
});
export const ABSTIME = registerKeyword({
  name: "ABSTIME",
});
export const ACCUM = registerKeyword({
  name: "ACCUM",
});
export const ACEE = registerKeyword({
  name: "ACEE",
});
export const ACQACTIVITY = registerKeyword({
  name: "ACQACTIVITY",
});
export const ACQPROCESS = registerKeyword({
  name: "ACQPROCESS",
  type: KeywordType.Control,
});
export const ACQUIRE = registerKeyword({
  name: "ACQUIRE",
  type: KeywordType.Control,
});
export const ACTION = registerKeyword({
  name: "ACTION",
});
export const ACTIVITY = registerKeyword({
  name: "ACTIVITY",
  type: KeywordType.Control,
});
export const ACTIVITYID = registerKeyword({
  name: "ACTIVITYID",
  type: KeywordType.Control,
});
export const ACTPARTN = registerKeyword({
  name: "ACTPARTN",
});
export const ADD = registerKeyword({
  name: "ADD",
  type: KeywordType.Control,
});
export const ADDRESS = registerKeyword({
  name: "ADDRESS",
  type: KeywordType.Control,
});
export const AFTER = registerKeyword({
  name: "AFTER",
});
export const AID = registerKeyword({
  name: "AID",
  type: KeywordType.Control,
});
export const ALARM = registerKeyword({
  name: "ALARM",
});
export const ALL = registerKeyword({
  name: "ALL",
});
export const ALTER = registerKeyword({
  name: "ALTER",
});
export const ALTERNATE = registerKeyword({
  name: "ALTERNATE",
});
export const ALTSCRNHT = registerKeyword({
  name: "ALTSCRNHT",
});
export const ALTSCRNWD = registerKeyword({
  name: "ALTSCRNWD",
});
export const ANY = registerKeyword({
  name: "ANY",
  type: KeywordType.Control,
});
export const ANYKEY = registerKeyword({
  name: "ANYKEY",
});
export const APLKYBD = registerKeyword({
  name: "APLKYBD",
});
export const APLTEXT = registerKeyword({
  name: "APLTEXT",
});
export const APPEND = registerKeyword({
  name: "APPEND",
});
export const APPLICATION = registerKeyword({
  name: "APPLICATION",
  type: KeywordType.Control,
});
export const APPLID = registerKeyword({
  name: "APPLID",
});
export const ASA = registerKeyword({
  name: "ASA",
});
export const ASIS = registerKeyword({
  name: "ASIS",
});
export const ASKTIME = registerKeyword({
  name: "ASKTIME",
  type: KeywordType.Control,
});
export const ASRAINTRPT = registerKeyword({
  name: "ASRAINTRPT",
});
export const ASRAKEY = registerKeyword({
  name: "ASRAKEY",
});
export const ASRAPSW = registerKeyword({
  name: "ASRAPSW",
});
export const ASRAPSW16 = registerKeyword({
  name: "ASRAPSW16",
});
export const ASRAREGS = registerKeyword({
  name: "ASRAREGS",
});
export const ASRAREGS64 = registerKeyword({
  name: "ASRAREGS64",
});
export const ASRASPC = registerKeyword({
  name: "ASRASPC",
});
export const ASRASTG = registerKeyword({
  name: "ASRASTG",
});
export const ASSIGN = registerKeyword({
  name: "ASSIGN",
  type: KeywordType.Control,
});
export const ASYNCHRONOUS = registerKeyword({
  name: "ASYNCHRONOUS",
});
export const AT = registerKeyword({
  name: "AT",
});
export const ATTACHID = registerKeyword({
  name: "ATTACHID",
});
export const ATTRIBUTES = registerKeyword({
  name: "ATTRIBUTES",
  type: KeywordType.Control,
});
export const AUTHENTICATE = registerKeyword({
  name: "AUTHENTICATE",
});
export const AUTOPAGE = registerKeyword({
  name: "AUTOPAGE",
});
export const AUXILIARY = registerKeyword({
  name: "AUXILIARY",
});
export const BASE64 = registerKeyword({
  name: "BASE64",
});
export const BASICAUTH = registerKeyword({
  name: "BASICAUTH",
});
export const BELOW = registerKeyword({
  name: "BELOW",
});
export const BIF = registerKeyword({
  name: "BIF",
  type: KeywordType.Control,
});
export const BODYCHARSET = registerKeyword({
  name: "BODYCHARSET",
});
export const BOOKMARK = registerKeyword({
  name: "BOOKMARK",
});
export const BRDATA = registerKeyword({
  name: "BRDATA",
});
export const BRDATALENGTH = registerKeyword({
  name: "BRDATALENGTH",
});
export const BREXIT = registerKeyword({
  name: "BREXIT",
  type: KeywordType.Control,
});
export const BRIDGE = registerKeyword({
  name: "BRIDGE",
});
export const BROWSETOKEN = registerKeyword({
  name: "BROWSETOKEN",
});
export const BTRANS = registerKeyword({
  name: "BTRANS",
});
export const BUFFER = registerKeyword({
  name: "BUFFER",
});
export const BUILD = registerKeyword({
  name: "BUILD",
  type: KeywordType.Control,
});
export const BYTEOFFSET = registerKeyword({
  name: "BYTEOFFSET",
});
export const CADDRLENGTH = registerKeyword({
  name: "CADDRLENGTH",
});
export const CARD = registerKeyword({
  name: "CARD",
});
export const CBUFF = registerKeyword({
  name: "CBUFF",
});
export const CCSID = registerKeyword({
  name: "CCSID",
});
export const CERTIFICATE = registerKeyword({
  name: "CERTIFICATE",
  type: KeywordType.Control,
});
export const CHANGE = registerKeyword({
  name: "CHANGE",
  type: KeywordType.Control,
});
export const CHANGETIME = registerKeyword({
  name: "CHANGETIME",
});
export const CHANNEL = registerKeyword({
  name: "CHANNEL",
  type: KeywordType.Control,
});
export const CHARACTERSET = registerKeyword({
  name: "CHARACTERSET",
});
export const CHECK = registerKeyword({
  name: "CHECK",
  type: KeywordType.Control,
});
export const CHILD = registerKeyword({
  name: "CHILD",
  type: KeywordType.Control,
});
export const CHUNKEND = registerKeyword({
  name: "CHUNKEND",
});
export const CHUNKING = registerKeyword({
  name: "CHUNKING",
});
export const CHUNKNO = registerKeyword({
  name: "CHUNKNO",
});
export const CHUNKYES = registerKeyword({
  name: "CHUNKYES",
});
export const CICSDATAKEY = registerKeyword({
  name: "CICSDATAKEY",
});
export const CIPHERS = registerKeyword({
  name: "CIPHERS",
});
export const CLASS = registerKeyword({
  name: "CLASS",
});
export const CLEAR = registerKeyword({
  name: "CLEAR",
});
export const CLICONVERT = registerKeyword({
  name: "CLICONVERT",
});
export const CLIENT = registerKeyword({
  name: "CLIENT",
});
export const CLIENTADDR = registerKeyword({
  name: "CLIENTADDR",
});
export const CLIENTADDRNU = registerKeyword({
  name: "CLIENTADDRNU",
});
export const CLIENTCONV = registerKeyword({
  name: "CLIENTCONV",
});
export const CLIENTNAME = registerKeyword({
  name: "CLIENTNAME",
});
export const CLNTADDR6NU = registerKeyword({
  name: "CLNTADDR6NU",
});
export const CLNTIPFAMILY = registerKeyword({
  name: "CLNTIPFAMILY",
});
export const CLOSESTATUS = registerKeyword({
  name: "CLOSESTATUS",
});
export const CLRPARTN = registerKeyword({
  name: "CLRPARTN",
});
export const CMDSEC = registerKeyword({
  name: "CMDSEC",
});
export const CNAMELENGTH = registerKeyword({
  name: "CNAMELENGTH",
});
export const CNOTCOMPL = registerKeyword({
  name: "CNOTCOMPL",
});
export const CODEPAGE = registerKeyword({
  name: "CODEPAGE",
});
export const COLOR = registerKeyword({
  name: "COLOR",
});
export const COMMAREA = registerKeyword({
  name: "COMMAREA",
});
export const COMMONNAME = registerKeyword({
  name: "COMMONNAME",
});
export const COMMONNAMLEN = registerKeyword({
  name: "COMMONNAMLEN",
});
export const COMPAREMAX = registerKeyword({
  name: "COMPAREMAX",
});
export const COMPAREMIN = registerKeyword({
  name: "COMPAREMIN",
});
export const COMPLETE = registerKeyword({
  name: "COMPLETE",
});
export const COMPOSITE = registerKeyword({
  name: "COMPOSITE",
  type: KeywordType.Control,
});
export const COMPSTATUS = registerKeyword({
  name: "COMPSTATUS",
});
export const CONFIRM = registerKeyword({
  name: "CONFIRM",
});
export const CONFIRMATION = registerKeyword({
  name: "CONFIRMATION",
  type: KeywordType.Control,
});
export const CONNECT = registerKeyword({
  name: "CONNECT",
  type: KeywordType.Control,
});
export const CONSISTENT = registerKeyword({
  name: "CONSISTENT",
});
export const CONSOLE = registerKeyword({
  name: "CONSOLE",
});
export const CONTAINER = registerKeyword({
  name: "CONTAINER",
  type: KeywordType.Control,
});
export const CONTAINERCNT = registerKeyword({
  name: "CONTAINERCNT",
});
export const CONTEXTTYPE = registerKeyword({
  name: "CONTEXTTYPE",
});
export const CONTROL = registerKeyword({
  name: "CONTROL",
  type: KeywordType.Control,
});
export const CONVDATA = registerKeyword({
  name: "CONVDATA",
});
export const CONVERSE = registerKeyword({
  name: "CONVERSE",
  type: KeywordType.Control,
});
export const CONVERTST = registerKeyword({
  name: "CONVERTST",
});
export const CONVERTTIME = registerKeyword({
  name: "CONVERTTIME",
  type: KeywordType.Control,
});
export const CONVID = registerKeyword({
  name: "CONVID",
  type: KeywordType.Control,
});
export const COUNTER = registerKeyword({
  name: "COUNTER",
  type: KeywordType.Control,
});
export const COUNTRY = registerKeyword({
  name: "COUNTRY",
});
export const COUNTRYLEN = registerKeyword({
  name: "COUNTRYLEN",
});
export const CREATE = registerKeyword({
  name: "CREATE",
  type: KeywordType.Control,
});
export const CRITICAL = registerKeyword({
  name: "CRITICAL",
});
export const CTLCHAR = registerKeyword({
  name: "CTLCHAR",
});
export const CURRENT = registerKeyword({
  name: "CURRENT",
});
export const CURSOR = registerKeyword({
  name: "CURSOR",
});
export const CWA = registerKeyword({
  name: "CWA",
});
export const CWALENG = registerKeyword({
  name: "CWALENG",
});
export const DATA1 = registerKeyword({
  name: "DATA1",
});
export const DATA2 = registerKeyword({
  name: "DATA2",
});
export const DATALENGTH = registerKeyword({
  name: "DATALENGTH",
});
export const DATAONLY = registerKeyword({
  name: "DATAONLY",
});
export const DATAPOINTER = registerKeyword({
  name: "DATAPOINTER",
});
export const DATASTR = registerKeyword({
  name: "DATASTR",
});
export const DATATOJSON = registerKeyword({
  name: "DATATOJSON",
  type: KeywordType.Control,
});
export const DATATOXML = registerKeyword({
  name: "DATATOXML",
  type: KeywordType.Control,
});
export const DATATYPE = registerKeyword({
  name: "DATATYPE",
});
export const DATCONTAINER = registerKeyword({
  name: "DATCONTAINER",
});
export const DATEFORM = registerKeyword({
  name: "DATEFORM",
});
export const DATESEP = registerKeyword({
  name: "DATESEP",
});
export const DATESTRING = registerKeyword({
  name: "DATESTRING",
});
export const DAYCOUNT = registerKeyword({
  name: "DAYCOUNT",
});
export const DAYOFMONTH = registerKeyword({
  name: "DAYOFMONTH",
});
export const DAYOFWEEK = registerKeyword({
  name: "DAYOFWEEK",
});
export const DAYOFYEAR = registerKeyword({
  name: "DAYOFYEAR",
});
export const DAYS = registerKeyword({
  name: "DAYS",
});
export const DAYSLEFT = registerKeyword({
  name: "DAYSLEFT",
});
export const DCOUNTER = registerKeyword({
  name: "DCOUNTER",
  type: KeywordType.Control,
});
export const DDMMYY = registerKeyword({
  name: "DDMMYY",
});
export const DDMMYYYY = registerKeyword({
  name: "DDMMYYYY",
});
export const DEBKEY = registerKeyword({
  name: "DEBKEY",
});
export const DEBREC = registerKeyword({
  name: "DEBREC",
});
export const DEEDIT = registerKeyword({
  name: "DEEDIT",
  type: KeywordType.Control,
});
export const DEFRESP = registerKeyword({
  name: "DEFRESP",
});
export const DEFSCRNHT = registerKeyword({
  name: "DEFSCRNHT",
});
export const DEFSCRNWD = registerKeyword({
  name: "DEFSCRNWD",
});
export const DELETEQ = registerKeyword({
  name: "DELETEQ",
  type: KeywordType.Control,
});
export const DELIMITER = registerKeyword({
  name: "DELIMITER",
});
export const DEQ = registerKeyword({
  name: "DEQ",
  type: KeywordType.Control,
});
export const DESTCOUNT = registerKeyword({
  name: "DESTCOUNT",
});
export const DESTID = registerKeyword({
  name: "DESTID",
});
export const DESTIDLENG = registerKeyword({
  name: "DESTIDLENG",
});
export const DETAIL = registerKeyword({
  name: "DETAIL",
});
export const DETAILLENGTH = registerKeyword({
  name: "DETAILLENGTH",
});
export const DIGEST = registerKeyword({
  name: "DIGEST",
  type: KeywordType.Control,
});
export const DIGESTTYPE = registerKeyword({
  name: "DIGESTTYPE",
});
export const DISCONNECT = registerKeyword({
  name: "DISCONNECT",
  type: KeywordType.Control,
});
export const DOCDELETE = registerKeyword({
  name: "DOCDELETE",
});
export const DOCSIZE = registerKeyword({
  name: "DOCSIZE",
});
export const DOCSTATUS = registerKeyword({
  name: "DOCSTATUS",
});
export const DOCTOKEN = registerKeyword({
  name: "DOCTOKEN",
});
export const DOCUMENT = registerKeyword({
  name: "DOCUMENT",
  type: KeywordType.Control,
});
export const DS3270 = registerKeyword({
  name: "DS3270",
});
export const DSSCS = registerKeyword({
  name: "DSSCS",
});
export const DUMP = registerKeyword({
  name: "DUMP",
  type: KeywordType.Control,
});
export const DUMPCODE = registerKeyword({
  name: "DUMPCODE",
});
export const DUMPID = registerKeyword({
  name: "DUMPID",
});
export const ECADDR = registerKeyword({
  name: "ECADDR",
});
export const ECBLIST = registerKeyword({
  name: "ECBLIST",
});
export const EIB = registerKeyword({
  name: "EIB",
});
export const ELEMNAME = registerKeyword({
  name: "ELEMNAME",
});
export const ELEMNAMELEN = registerKeyword({
  name: "ELEMNAMELEN",
});
export const ELEMNS = registerKeyword({
  name: "ELEMNS",
});
export const ELEMNSLEN = registerKeyword({
  name: "ELEMNSLEN",
});
export const ENCRYPTKEY = registerKeyword({
  name: "ENCRYPTKEY",
});
export const ENCRYPTPTKT = registerKeyword({
  name: "ENCRYPTPTKT",
  type: KeywordType.Control,
});
export const ENDACTIVITY = registerKeyword({
  name: "ENDACTIVITY",
});
export const ENDBR = registerKeyword({
  name: "ENDBR",
  type: KeywordType.Control,
});
export const ENDBROWSE = registerKeyword({
  name: "ENDBROWSE",
  type: KeywordType.Control,
});
export const ENDOUTPUT = registerKeyword({
  name: "ENDOUTPUT",
  type: KeywordType.Control,
});
export const ENQ = registerKeyword({
  name: "ENQ",
  type: KeywordType.Control,
});
export const ENTER = registerKeyword({
  name: "ENTER",
  type: KeywordType.Control,
});
export const ENTRYNAME = registerKeyword({
  name: "ENTRYNAME",
});
export const EODS = registerKeyword({
  name: "EODS",
  type: KeywordType.Control,
});
export const EPRFIELD = registerKeyword({
  name: "EPRFIELD",
});
export const EPRFROM = registerKeyword({
  name: "EPRFROM",
});
export const EPRINTO = registerKeyword({
  name: "EPRINTO",
});
export const EPRLENGTH = registerKeyword({
  name: "EPRLENGTH",
});
export const EPRSET = registerKeyword({
  name: "EPRSET",
});
export const EPRTYPE = registerKeyword({
  name: "EPRTYPE",
});
export const EQUAL = registerKeyword({
  name: "EQUAL",
});
export const ERASE = registerKeyword({
  name: "ERASE",
  type: KeywordType.Control,
});
export const ERASEAUP = registerKeyword({
  name: "ERASEAUP",
  type: KeywordType.Control,
});
export const ERRORMSG = registerKeyword({
  name: "ERRORMSG",
});
export const ERRORMSGLEN = registerKeyword({
  name: "ERRORMSGLEN",
});
export const ERRTERM = registerKeyword({
  name: "ERRTERM",
});
export const ESMAPPNAME = registerKeyword({
  name: "ESMAPPNAME",
});
export const ESMREASON = registerKeyword({
  name: "ESMREASON",
});
export const ESMRESP = registerKeyword({
  name: "ESMRESP",
});
export const EVENTTYPE = registerKeyword({
  name: "EVENTTYPE",
});
export const EVENTUAL = registerKeyword({
  name: "EVENTUAL",
});
export const EWASUPP = registerKeyword({
  name: "EWASUPP",
});
export const EXACTMATCH = registerKeyword({
  name: "EXACTMATCH",
});
export const EXCEPTION = registerKeyword({
  name: "EXCEPTION",
});
export const EXPECT = registerKeyword({
  name: "EXPECT",
});
export const EXPIRYTIME = registerKeyword({
  name: "EXPIRYTIME",
});
export const EXTDS = registerKeyword({
  name: "EXTDS",
});
export const EXTRACT = registerKeyword({
  name: "EXTRACT",
  type: KeywordType.Control,
});
export const FACILITY = registerKeyword({
  name: "FACILITY",
});
export const FACILITYTOKN = registerKeyword({
  name: "FACILITYTOKN",
});
export const FAULTACTLEN = registerKeyword({
  name: "FAULTACTLEN",
});
export const FAULTACTOR = registerKeyword({
  name: "FAULTACTOR",
});
export const FAULTCODE = registerKeyword({
  name: "FAULTCODE",
});
export const FAULTCODELEN = registerKeyword({
  name: "FAULTCODELEN",
});
export const FAULTCODESTR = registerKeyword({
  name: "FAULTCODESTR",
});
export const FAULTSTRING = registerKeyword({
  name: "FAULTSTRING",
});
export const FAULTSTRLEN = registerKeyword({
  name: "FAULTSTRLEN",
});
export const FCI = registerKeyword({
  name: "FCI",
});
export const FCT = registerKeyword({
  name: "FCT",
});
export const FIELD = registerKeyword({
  name: "FIELD",
});
export const FIRESTATUS = registerKeyword({
  name: "FIRESTATUS",
});
export const FLENGTH = registerKeyword({
  name: "FLENGTH",
});
export const FMH = registerKeyword({
  name: "FMH",
});
export const FMHPARM = registerKeyword({
  name: "FMHPARM",
});
export const FOR = registerKeyword({
  name: "FOR",
});
export const FORCE = registerKeyword({
  name: "FORCE",
  type: KeywordType.Control,
});
export const FORMATTIME = registerKeyword({
  name: "FORMATTIME",
  type: KeywordType.Control,
});
export const FORMFEED = registerKeyword({
  name: "FORMFEED",
});
export const FORMFIELD = registerKeyword({
  name: "FORMFIELD",
  type: KeywordType.Control,
});
export const FREEKB = registerKeyword({
  name: "FREEKB",
});
export const FREEMAIN = registerKeyword({
  name: "FREEMAIN",
  type: KeywordType.Control,
});
export const FREEMAIN64 = registerKeyword({
  name: "FREEMAIN64",
  type: KeywordType.Control,
});
export const FROMACTIVITY = registerKeyword({
  name: "FROMACTIVITY",
});
export const FROMCCSID = registerKeyword({
  name: "FROMCCSID",
});
export const FROMCHANNEL = registerKeyword({
  name: "FROMCHANNEL",
});
export const FROMCODEPAGE = registerKeyword({
  name: "FROMCODEPAGE",
});
export const FROMDOC = registerKeyword({
  name: "FROMDOC",
});
export const FROMFLENGTH = registerKeyword({
  name: "FROMFLENGTH",
});
export const FROMLENGTH = registerKeyword({
  name: "FROMLENGTH",
});
export const FROMPROCESS = registerKeyword({
  name: "FROMPROCESS",
});
export const FRSET = registerKeyword({
  name: "FRSET",
});
export const FULLDATE = registerKeyword({
  name: "FULLDATE",
});
export const GCHARS = registerKeyword({
  name: "GCHARS",
});
export const GCODES = registerKeyword({
  name: "GCODES",
});
export const GDS = registerKeyword({
  name: "GDS",
  type: KeywordType.Control,
});
export const GET64 = registerKeyword({
  name: "GET64",
  type: KeywordType.Control,
});
export const GETMAIN = registerKeyword({
  name: "GETMAIN",
  type: KeywordType.Control,
});
export const GETMAIN64 = registerKeyword({
  name: "GETMAIN64",
  type: KeywordType.Control,
});
export const GETNEXT = registerKeyword({
  name: "GETNEXT",
  type: KeywordType.Control,
});
export const GMMI = registerKeyword({
  name: "GMMI",
});
export const GROUPID = registerKeyword({
  name: "GROUPID",
});
export const GTEQ = registerKeyword({
  name: "GTEQ",
});
export const HEAD = registerKeyword({
  name: "HEAD",
});
export const HEADER = registerKeyword({
  name: "HEADER",
});
export const HEX = registerKeyword({
  name: "HEX",
});
export const HILIGHT = registerKeyword({
  name: "HILIGHT",
});
export const HOLD = registerKeyword({
  name: "HOLD",
});
export const HONEOM = registerKeyword({
  name: "HONEOM",
});
export const HOST = registerKeyword({
  name: "HOST",
});
export const HOSTCODEPAGE = registerKeyword({
  name: "HOSTCODEPAGE",
});
export const HOSTLENGTH = registerKeyword({
  name: "HOSTLENGTH",
});
export const HOSTTYPE = registerKeyword({
  name: "HOSTTYPE",
});
export const HOURS = registerKeyword({
  name: "HOURS",
});
export const HTTPHEADER = registerKeyword({
  name: "HTTPHEADER",
  type: KeywordType.Control,
});
export const HTTPMETHOD = registerKeyword({
  name: "HTTPMETHOD",
});
export const HTTPRNUM = registerKeyword({
  name: "HTTPRNUM",
});
export const HTTPVERSION = registerKeyword({
  name: "HTTPVERSION",
});
export const HTTPVNUM = registerKeyword({
  name: "HTTPVNUM",
});
export const IMMEDIATE = registerKeyword({
  name: "IMMEDIATE",
});
export const INCONTAINER = registerKeyword({
  name: "INCONTAINER",
});
export const INCREMENT = registerKeyword({
  name: "INCREMENT",
});
export const INITIMG = registerKeyword({
  name: "INITIMG",
});
export const INITPARM = registerKeyword({
  name: "INITPARM",
});
export const INITPARMLEN = registerKeyword({
  name: "INITPARMLEN",
});
export const INPARTN = registerKeyword({
  name: "INPARTN",
});
export const INPUTEVENT = registerKeyword({
  name: "INPUTEVENT",
});
export const INPUTMSG = registerKeyword({
  name: "INPUTMSG",
});
export const INPUTMSGLEN = registerKeyword({
  name: "INPUTMSGLEN",
});
export const INQUIRE = registerKeyword({
  name: "INQUIRE",
  type: KeywordType.Control,
});
export const INSERT = registerKeyword({
  name: "INSERT",
  type: KeywordType.Control,
});
export const INTERVAL = registerKeyword({
  name: "INTERVAL",
});
export const INTOCCSID = registerKeyword({
  name: "INTOCCSID",
});
export const INTOCODEPAGE = registerKeyword({
  name: "INTOCODEPAGE",
});
export const INVALIDCOUNT = registerKeyword({
  name: "INVALIDCOUNT",
});
export const INVITE = registerKeyword({
  name: "INVITE",
});
export const INVOKE = registerKeyword({
  name: "INVOKE",
  type: KeywordType.Control,
});
export const INVOKINGPROG = registerKeyword({
  name: "INVOKINGPROG",
});
export const ISSUE = registerKeyword({
  name: "ISSUE",
  type: KeywordType.Control,
});
export const ISSUER = registerKeyword({
  name: "ISSUER",
});
export const ISUSERID = registerKeyword({
  name: "ISUSERID",
});
export const ITEM = registerKeyword({
  name: "ITEM",
});
export const IUTYPE = registerKeyword({
  name: "IUTYPE",
});
export const JOURNAL = registerKeyword({
  name: "JOURNAL",
  type: KeywordType.Control,
});
export const JOURNALNAME = registerKeyword({
  name: "JOURNALNAME",
  type: KeywordType.Control,
});
export const JOURNALNUM = registerKeyword({
  name: "JOURNALNUM",
  type: KeywordType.Control,
});
export const JSONTODATA = registerKeyword({
  name: "JSONTODATA",
  type: KeywordType.Control,
});
export const JTYPEID = registerKeyword({
  name: "JTYPEID",
});
export const JUSFIRST = registerKeyword({
  name: "JUSFIRST",
});
export const JUSLAST = registerKeyword({
  name: "JUSLAST",
});
export const JUSTIFY = registerKeyword({
  name: "JUSTIFY",
});
export const JWT = registerKeyword({
  name: "JWT",
});
export const KATAKANA = registerKeyword({
  name: "KATAKANA",
});
export const KEEP = registerKeyword({
  name: "KEEP",
});
export const KERBEROS = registerKeyword({
  name: "KERBEROS",
});
export const KEYLENGTH = registerKeyword({
  name: "KEYLENGTH",
});
export const KEYNUMBER = registerKeyword({
  name: "KEYNUMBER",
});
export const L40 = registerKeyword({
  name: "L40",
});
export const L64 = registerKeyword({
  name: "L64",
});
export const L80 = registerKeyword({
  name: "L80",
});
export const LANGINUSE = registerKeyword({
  name: "LANGINUSE",
});
export const LANGUAGECODE = registerKeyword({
  name: "LANGUAGECODE",
});
export const LAST = registerKeyword({
  name: "LAST",
});
export const LASTUSETIME = registerKeyword({
  name: "LASTUSETIME",
});
export const LDC = registerKeyword({
  name: "LDC",
});
export const LDCMNEM = registerKeyword({
  name: "LDCMNEM",
});
export const LDCNUM = registerKeyword({
  name: "LDCNUM",
});
export const LEAVEKB = registerKeyword({
  name: "LEAVEKB",
});
export const LENGTH = registerKeyword({
  name: "LENGTH",
});
export const LENGTHLIST = registerKeyword({
  name: "LENGTHLIST",
});
export const LEVEL = registerKeyword({
  name: "LEVEL",
});
export const LIGHTPEN = registerKeyword({
  name: "LIGHTPEN",
});
export const LINEADDR = registerKeyword({
  name: "LINEADDR",
});
export const LINK = registerKeyword({
  name: "LINK",
  type: KeywordType.Control,
});
export const LINKLEVEL = registerKeyword({
  name: "LINKLEVEL",
});
export const LISTLENGTH = registerKeyword({
  name: "LISTLENGTH",
});
export const LLID = registerKeyword({
  name: "LLID",
});
export const LOAD = registerKeyword({
  name: "LOAD",
  type: KeywordType.Control,
});
export const LOCALCCSID = registerKeyword({
  name: "LOCALCCSID",
});
export const LOCALITY = registerKeyword({
  name: "LOCALITY",
});
export const LOCALITYLEN = registerKeyword({
  name: "LOCALITYLEN",
});
export const LOCATION = registerKeyword({
  name: "LOCATION",
});
export const LOGMESSAGE = registerKeyword({
  name: "LOGMESSAGE",
});
export const LOGMODE = registerKeyword({
  name: "LOGMODE",
});
export const LOGONLOGMODE = registerKeyword({
  name: "LOGONLOGMODE",
});
export const LOGONMSG = registerKeyword({
  name: "LOGONMSG",
  type: KeywordType.Control,
});
export const LUNAME = registerKeyword({
  name: "LUNAME",
});
export const MAJORVERSION = registerKeyword({
  name: "MAJORVERSION",
});
export const MAP = registerKeyword({
  name: "MAP",
  type: KeywordType.Control,
});
export const MAPCOLUMN = registerKeyword({
  name: "MAPCOLUMN",
});
export const MAPHEIGHT = registerKeyword({
  name: "MAPHEIGHT",
});
export const MAPLINE = registerKeyword({
  name: "MAPLINE",
});
export const MAPONLY = registerKeyword({
  name: "MAPONLY",
});
export const MAPPED = registerKeyword({
  name: "MAPPED",
  type: KeywordType.Control,
});
export const MAPPINGDEV = registerKeyword({
  name: "MAPPINGDEV",
  type: KeywordType.Control,
});
export const MAPSET = registerKeyword({
  name: "MAPSET",
});
export const MAPWIDTH = registerKeyword({
  name: "MAPWIDTH",
});
export const MASSINSERT = registerKeyword({
  name: "MASSINSERT",
});
export const MAXDATALEN = registerKeyword({
  name: "MAXDATALEN",
});
export const MAXFLENGTH = registerKeyword({
  name: "MAXFLENGTH",
});
export const MAXIMUM = registerKeyword({
  name: "MAXIMUM",
});
export const MAXLENGTH = registerKeyword({
  name: "MAXLENGTH",
});
export const MAXLIFETIME = registerKeyword({
  name: "MAXLIFETIME",
});
export const MAXPROCLEN = registerKeyword({
  name: "MAXPROCLEN",
});
export const MCC = registerKeyword({
  name: "MCC",
});
export const MEDIATYPE = registerKeyword({
  name: "MEDIATYPE",
});
export const MESSAGE = registerKeyword({
  name: "MESSAGE",
  type: KeywordType.Control,
});
export const MESSAGEID = registerKeyword({
  name: "MESSAGEID",
});
export const METADATA = registerKeyword({
  name: "METADATA",
});
export const METADATALEN = registerKeyword({
  name: "METADATALEN",
});
export const METHOD = registerKeyword({
  name: "METHOD",
});
export const METHODLENGTH = registerKeyword({
  name: "METHODLENGTH",
});
export const MICROVERSION = registerKeyword({
  name: "MICROVERSION",
});
export const MILLISECONDS = registerKeyword({
  name: "MILLISECONDS",
});
export const MILLISECS = registerKeyword({
  name: "MILLISECS",
});
export const MINIMUM = registerKeyword({
  name: "MINIMUM",
});
export const MINORVERSION = registerKeyword({
  name: "MINORVERSION",
});
export const MINUTES = registerKeyword({
  name: "MINUTES",
});
export const MMDDYY = registerKeyword({
  name: "MMDDYY",
});
export const MMDDYYYY = registerKeyword({
  name: "MMDDYYYY",
});
export const MODE = registerKeyword({
  name: "MODE",
});
export const MODENAME = registerKeyword({
  name: "MODENAME",
});
export const MONITOR = registerKeyword({
  name: "MONITOR",
  type: KeywordType.Control,
});
export const MONTH = registerKeyword({
  name: "MONTH",
});
export const MONTHOFYEAR = registerKeyword({
  name: "MONTHOFYEAR",
});
export const MOVE = registerKeyword({
  name: "MOVE",
  type: KeywordType.Control,
});
export const MSR = registerKeyword({
  name: "MSR",
});
export const MSRCONTROL = registerKeyword({
  name: "MSRCONTROL",
});
export const NAMELENGTH = registerKeyword({
  name: "NAMELENGTH",
});
export const NATLANG = registerKeyword({
  name: "NATLANG",
});
export const NATLANGINUSE = registerKeyword({
  name: "NATLANGINUSE",
});
export const NETNAME = registerKeyword({
  name: "NETNAME",
});
export const NEWPASSWORD = registerKeyword({
  name: "NEWPASSWORD",
});
export const NEWPHRASE = registerKeyword({
  name: "NEWPHRASE",
});
export const NEWPHRASELEN = registerKeyword({
  name: "NEWPHRASELEN",
});
export const NEXT = registerKeyword({
  name: "NEXT",
});
export const NEXTTRANSID = registerKeyword({
  name: "NEXTTRANSID",
});
export const NLEOM = registerKeyword({
  name: "NLEOM",
});
export const NOAUTOPAGE = registerKeyword({
  name: "NOAUTOPAGE",
});
export const NOCC = registerKeyword({
  name: "NOCC",
});
export const NOCHECK = registerKeyword({
  name: "NOCHECK",
});
export const NOCLICONVERT = registerKeyword({
  name: "NOCLICONVERT",
});
export const NOCLOSE = registerKeyword({
  name: "NOCLOSE",
});
export const NODATA = registerKeyword({
  name: "NODATA",
});
export const NODE = registerKeyword({
  name: "NODE",
});
export const NODOCDELETE = registerKeyword({
  name: "NODOCDELETE",
});
export const NODUMP = registerKeyword({
  name: "NODUMP",
});
export const NOEDIT = registerKeyword({
  name: "NOEDIT",
  type: KeywordType.Control,
});
export const NOFLUSH = registerKeyword({
  name: "NOFLUSH",
});
export const NOHANDLE = registerKeyword({
  name: "NOHANDLE",
});
export const NOINCONVERT = registerKeyword({
  name: "NOINCONVERT",
});
export const NONE = registerKeyword({
  name: "NONE",
});
export const NOOUTCONVERT = registerKeyword({
  name: "NOOUTCONVERT",
});
export const NOQUEUE = registerKeyword({
  name: "NOQUEUE",
});
export const NOQUIESCE = registerKeyword({
  name: "NOQUIESCE",
});
export const NOSRVCONVERT = registerKeyword({
  name: "NOSRVCONVERT",
});
export const NOSUSPEND = registerKeyword({
  name: "NOSUSPEND",
});
export const NOTPURGEABLE = registerKeyword({
  name: "NOTPURGEABLE",
});
export const NOTRUNCATE = registerKeyword({
  name: "NOTRUNCATE",
});
export const NOWAIT = registerKeyword({
  name: "NOWAIT",
});
export const NSCONTAINER = registerKeyword({
  name: "NSCONTAINER",
});
export const NUMCIPHERS = registerKeyword({
  name: "NUMCIPHERS",
});
export const NUMEVENTS = registerKeyword({
  name: "NUMEVENTS",
});
export const NUMITEMS = registerKeyword({
  name: "NUMITEMS",
});
export const NUMREC = registerKeyword({
  name: "NUMREC",
});
export const NUMROUTES = registerKeyword({
  name: "NUMROUTES",
});
export const NUMSEGMENTS = registerKeyword({
  name: "NUMSEGMENTS",
});
export const NUMTAB = registerKeyword({
  name: "NUMTAB",
});
export const OIDCARD = registerKeyword({
  name: "OIDCARD",
});
export const OPCLASS = registerKeyword({
  name: "OPCLASS",
});
export const OPERATION = registerKeyword({
  name: "OPERATION",
});
export const OPERATOR = registerKeyword({
  name: "OPERATOR",
  type: KeywordType.Control,
});
export const OPERID = registerKeyword({
  name: "OPERID",
});
export const OPERKEYS = registerKeyword({
  name: "OPERKEYS",
});
export const OPERPURGE = registerKeyword({
  name: "OPERPURGE",
});
export const OPID = registerKeyword({
  name: "OPID",
});
export const OPSECURITY = registerKeyword({
  name: "OPSECURITY",
});
export const ORGABCODE = registerKeyword({
  name: "ORGABCODE",
});
export const ORGANIZATLEN = registerKeyword({
  name: "ORGANIZATLEN",
});
export const ORGUNIT = registerKeyword({
  name: "ORGUNIT",
});
export const ORGUNITLEN = registerKeyword({
  name: "ORGUNITLEN",
});
export const OUTCONTAINER = registerKeyword({
  name: "OUTCONTAINER",
});
export const OUTDESCR = registerKeyword({
  name: "OUTDESCR",
});
export const OUTLINE = registerKeyword({
  name: "OUTLINE",
});
export const OUTPARTN = registerKeyword({
  name: "OUTPARTN",
});
export const OUTTOKEN = registerKeyword({
  name: "OUTTOKEN",
});
export const OUTTOKENLEN = registerKeyword({
  name: "OUTTOKENLEN",
});
export const OWNER = registerKeyword({
  name: "OWNER",
});
export const PA1 = registerKeyword({
  name: "PA1",
});
export const PA3 = registerKeyword({
  name: "PA3",
});
export const PAGENUM = registerKeyword({
  name: "PAGENUM",
});
export const PAGING = registerKeyword({
  name: "PAGING",
});
export const PARSE = registerKeyword({
  name: "PARSE",
  type: KeywordType.Control,
});
export const PARTN = registerKeyword({
  name: "PARTN",
  type: KeywordType.Control,
});
export const PARTNER = registerKeyword({
  name: "PARTNER",
});
export const PARTNPAGE = registerKeyword({
  name: "PARTNPAGE",
});
export const PARTNS = registerKeyword({
  name: "PARTNS",
});
export const PARTNSET = registerKeyword({
  name: "PARTNSET",
  type: KeywordType.Control,
});
export const PASS = registerKeyword({
  name: "PASS",
  type: KeywordType.Control,
});
export const PASSBK = registerKeyword({
  name: "PASSBK",
});
export const PASSTICKET = registerKeyword({
  name: "PASSTICKET",
  type: KeywordType.Control,
});
export const PASSWORDLEN = registerKeyword({
  name: "PASSWORDLEN",
});
export const PATCH = registerKeyword({
  name: "PATCH",
});
export const PATH = registerKeyword({
  name: "PATH",
});
export const PATHLENGTH = registerKeyword({
  name: "PATHLENGTH",
});
export const PCT = registerKeyword({
  name: "PCT",
});
export const PF1 = registerKeyword({
  name: "PF1",
});
export const PF24 = registerKeyword({
  name: "PF24",
});
export const PFXLENG = registerKeyword({
  name: "PFXLENG",
});
export const PHRASE = registerKeyword({
  name: "PHRASE",
  type: KeywordType.Control,
});
export const PHRASELEN = registerKeyword({
  name: "PHRASELEN",
});
export const PIPLENGTH = registerKeyword({
  name: "PIPLENGTH",
});
export const PIPLIST = registerKeyword({
  name: "PIPLIST",
});
export const PLATFORM = registerKeyword({
  name: "PLATFORM",
});
export const POINT = registerKeyword({
  name: "POINT",
  type: KeywordType.Control,
});
export const POOL = registerKeyword({
  name: "POOL",
});
export const PORTNUMBER = registerKeyword({
  name: "PORTNUMBER",
});
export const PORTNUMNU = registerKeyword({
  name: "PORTNUMNU",
});
export const POST = registerKeyword({
  name: "POST",
  type: KeywordType.Control,
});
export const PPT = registerKeyword({
  name: "PPT",
});
export const PREDICATE = registerKeyword({
  name: "PREDICATE",
});
export const PREFIX = registerKeyword({
  name: "PREFIX",
});
export const PREPARE = registerKeyword({
  name: "PREPARE",
  type: KeywordType.Control,
});
export const PRINCONVID = registerKeyword({
  name: "PRINCONVID",
});
export const PRINSYSID = registerKeyword({
  name: "PRINSYSID",
});
export const PRIORITY = registerKeyword({
  name: "PRIORITY",
});
export const PRIVACY = registerKeyword({
  name: "PRIVACY",
});
export const PROCESSTYPE = registerKeyword({
  name: "PROCESSTYPE",
});
export const PROCLENGTH = registerKeyword({
  name: "PROCLENGTH",
});
export const PROCNAME = registerKeyword({
  name: "PROCNAME",
});
export const PROFILE = registerKeyword({
  name: "PROFILE",
});
export const PROGRAM = registerKeyword({
  name: "PROGRAM",
});
export const PROTECT = registerKeyword({
  name: "PROTECT",
});
export const PS = registerKeyword({
  name: "PS",
});
export const PUNCH = registerKeyword({
  name: "PUNCH",
});
export const PURGE = registerKeyword({
  name: "PURGE",
  type: KeywordType.Control,
});
export const PURGEABILITY = registerKeyword({
  name: "PURGEABILITY",
});
export const PURGEABLE = registerKeyword({
  name: "PURGEABLE",
});
export const PUT64 = registerKeyword({
  name: "PUT64",
  type: KeywordType.Control,
});
export const QNAME = registerKeyword({
  name: "QNAME",
});
export const QUERY = registerKeyword({
  name: "QUERY",
  type: KeywordType.Control,
});
export const QUERYPARM = registerKeyword({
  name: "QUERYPARM",
  type: KeywordType.Control,
});
export const QUERYSTRING = registerKeyword({
  name: "QUERYSTRING",
});
export const QUERYSTRLEN = registerKeyword({
  name: "QUERYSTRLEN",
});
export const QUEUE = registerKeyword({
  name: "QUEUE",
});
export const RBA = registerKeyword({
  name: "RBA",
});
export const READNEXT = registerKeyword({
  name: "READNEXT",
  type: KeywordType.Control,
});
export const READPREV = registerKeyword({
  name: "READPREV",
  type: KeywordType.Control,
});
export const READQ = registerKeyword({
  name: "READQ",
  type: KeywordType.Control,
});
export const REALM = registerKeyword({
  name: "REALM",
});
export const REALMLEN = registerKeyword({
  name: "REALMLEN",
});
export const REATTACH = registerKeyword({
  name: "REATTACH",
  type: KeywordType.Control,
});
export const RECEIVE = registerKeyword({
  name: "RECEIVE",
  type: KeywordType.Control,
});
export const RECEIVER = registerKeyword({
  name: "RECEIVER",
});
export const RECFM = registerKeyword({
  name: "RECFM",
});
export const RECORDLEN = registerKeyword({
  name: "RECORDLEN",
});
export const RECORDLENGTH = registerKeyword({
  name: "RECORDLENGTH",
});
export const REDUCE = registerKeyword({
  name: "REDUCE",
});
export const REFPARMS = registerKeyword({
  name: "REFPARMS",
});
export const REFPARMSLEN = registerKeyword({
  name: "REFPARMSLEN",
});
export const RELATESINDEX = registerKeyword({
  name: "RELATESINDEX",
});
export const RELATESTYPE = registerKeyword({
  name: "RELATESTYPE",
});
export const RELATESURI = registerKeyword({
  name: "RELATESURI",
});
export const REMOVE = registerKeyword({
  name: "REMOVE",
  type: KeywordType.Control,
});
export const REPEATABLE = registerKeyword({
  name: "REPEATABLE",
});
export const REPLYLENGTH = registerKeyword({
  name: "REPLYLENGTH",
});
export const REQID = registerKeyword({
  name: "REQID",
});
export const REQUEST = registerKeyword({
  name: "REQUEST",
  type: KeywordType.Control,
});
export const REQUESTTYPE = registerKeyword({
  name: "REQUESTTYPE",
});
export const RESCLASS = registerKeyword({
  name: "RESCLASS",
});
export const RESET = registerKeyword({
  name: "RESET",
  type: KeywordType.Control,
});
export const RESETBR = registerKeyword({
  name: "RESETBR",
  type: KeywordType.Control,
});
export const RESID = registerKeyword({
  name: "RESID",
});
export const RESIDLENGTH = registerKeyword({
  name: "RESIDLENGTH",
});
export const RESOURCE = registerKeyword({
  name: "RESOURCE",
});
export const RESP = registerKeyword({
  name: "RESP",
});
export const RESP2 = registerKeyword({
  name: "RESP2",
});
export const RESSEC = registerKeyword({
  name: "RESSEC",
});
export const RESTART = registerKeyword({
  name: "RESTART",
});
export const RESTYPE = registerKeyword({
  name: "RESTYPE",
});
export const RESULT = registerKeyword({
  name: "RESULT",
});
export const RESUME = registerKeyword({
  name: "RESUME",
  type: KeywordType.Control,
});
export const RETAIN = registerKeyword({
  name: "RETAIN",
});
export const RETRIEVE = registerKeyword({
  name: "RETRIEVE",
  type: KeywordType.Control,
});
export const RETURNPROG = registerKeyword({
  name: "RETURNPROG",
});
export const REWIND = registerKeyword({
  name: "REWIND",
  type: KeywordType.Control,
});
export const RIDFLD = registerKeyword({
  name: "RIDFLD",
});
export const ROLE = registerKeyword({
  name: "ROLE",
});
export const ROLELENGTH = registerKeyword({
  name: "ROLELENGTH",
});
export const ROLLBACK = registerKeyword({
  name: "ROLLBACK",
  type: KeywordType.Control,
});
export const ROUTE = registerKeyword({
  name: "ROUTE",
  type: KeywordType.Control,
});
export const ROUTECODES = registerKeyword({
  name: "ROUTECODES",
});
export const RPROCESS = registerKeyword({
  name: "RPROCESS",
});
export const RRESOURCE = registerKeyword({
  name: "RRESOURCE",
});
export const RRN = registerKeyword({
  name: "RRN",
});
export const RTERMID = registerKeyword({
  name: "RTERMID",
});
export const RTRANSID = registerKeyword({
  name: "RTRANSID",
});
export const RUN = registerKeyword({
  name: "RUN",
  type: KeywordType.Control,
});
export const SADDRLENGTH = registerKeyword({
  name: "SADDRLENGTH",
});
export const SCHEME = registerKeyword({
  name: "SCHEME",
});
export const SCHEMENAME = registerKeyword({
  name: "SCHEMENAME",
});
export const SCOPE = registerKeyword({
  name: "SCOPE",
});
export const SCOPELEN = registerKeyword({
  name: "SCOPELEN",
});
export const SCRNHT = registerKeyword({
  name: "SCRNHT",
});
export const SCRNWD = registerKeyword({
  name: "SCRNWD",
});
export const SECONDS = registerKeyword({
  name: "SECONDS",
});
export const SECURITY = registerKeyword({
  name: "SECURITY",
  type: KeywordType.Control,
});
export const SEGMENTLIST = registerKeyword({
  name: "SEGMENTLIST",
});
export const SEND = registerKeyword({
  name: "SEND",
  type: KeywordType.Control,
});
export const SENDER = registerKeyword({
  name: "SENDER",
});
export const SERIALNUM = registerKeyword({
  name: "SERIALNUM",
});
export const SERIALNUMLEN = registerKeyword({
  name: "SERIALNUMLEN",
});
export const SERVER = registerKeyword({
  name: "SERVER",
});
export const SERVERADDR = registerKeyword({
  name: "SERVERADDR",
});
export const SERVERADDRNU = registerKeyword({
  name: "SERVERADDRNU",
});
export const SERVERCONV = registerKeyword({
  name: "SERVERCONV",
});
export const SERVERNAME = registerKeyword({
  name: "SERVERNAME",
});
export const SERVICE = registerKeyword({
  name: "SERVICE",
  type: KeywordType.Control,
});
export const SESSION = registerKeyword({
  name: "SESSION",
});
export const SESSTOKEN = registerKeyword({
  name: "SESSTOKEN",
});
export const SHARED = registerKeyword({
  name: "SHARED",
});
export const SIGDATA = registerKeyword({
  name: "SIGDATA",
});
export const SIGNOFF = registerKeyword({
  name: "SIGNOFF",
  type: KeywordType.Control,
});
export const SIGNON = registerKeyword({
  name: "SIGNON",
  type: KeywordType.Control,
});
export const SIT = registerKeyword({
  name: "SIT",
});
export const SNAMELENGTH = registerKeyword({
  name: "SNAMELENGTH",
});
export const SOAPFAULT = registerKeyword({
  name: "SOAPFAULT",
  type: KeywordType.Control,
});
export const SOSI = registerKeyword({
  name: "SOSI",
});
export const SPOOLCLOSE = registerKeyword({
  name: "SPOOLCLOSE",
  type: KeywordType.Control,
});
export const SPOOLOPEN = registerKeyword({
  name: "SPOOLOPEN",
  type: KeywordType.Control,
});
export const SPOOLREAD = registerKeyword({
  name: "SPOOLREAD",
  type: KeywordType.Control,
});
export const SPOOLWRITE = registerKeyword({
  name: "SPOOLWRITE",
  type: KeywordType.Control,
});
export const SRVCONVERT = registerKeyword({
  name: "SRVCONVERT",
});
export const SRVRADDR6NU = registerKeyword({
  name: "SRVRADDR6NU",
});
export const SRVRIPFAMILY = registerKeyword({
  name: "SRVRIPFAMILY",
});
export const SSLTYPE = registerKeyword({
  name: "SSLTYPE",
});
export const START = registerKeyword({
  name: "START",
  type: KeywordType.Control,
});
export const STARTBR = registerKeyword({
  name: "STARTBR",
  type: KeywordType.Control,
});
export const STARTBROWSE = registerKeyword({
  name: "STARTBROWSE",
  type: KeywordType.Control,
});
export const STARTCODE = registerKeyword({
  name: "STARTCODE",
});
export const STATE = registerKeyword({
  name: "STATE",
});
export const STATELEN = registerKeyword({
  name: "STATELEN",
});
export const STATIONID = registerKeyword({
  name: "STATIONID",
});
export const STATUS = registerKeyword({
  name: "STATUS",
});
export const STATUSCODE = registerKeyword({
  name: "STATUSCODE",
});
export const STATUSLEN = registerKeyword({
  name: "STATUSLEN",
});
export const STATUSTEXT = registerKeyword({
  name: "STATUSTEXT",
});
export const STRFIELD = registerKeyword({
  name: "STRFIELD",
});
export const STRINGFORMAT = registerKeyword({
  name: "STRINGFORMAT",
});
export const STRINGZONE = registerKeyword({
  name: "STRINGZONE",
});
export const SUBADDR = registerKeyword({
  name: "SUBADDR",
});
export const SUBCODELEN = registerKeyword({
  name: "SUBCODELEN",
});
export const SUBCODESTR = registerKeyword({
  name: "SUBCODESTR",
});
export const SUBEVENT = registerKeyword({
  name: "SUBEVENT",
  type: KeywordType.Control,
});
export const SUBEVENT1 = registerKeyword({
  name: "SUBEVENT1",
});
export const SUBEVENT2 = registerKeyword({
  name: "SUBEVENT2",
});
export const SUBEVENT3 = registerKeyword({
  name: "SUBEVENT3",
});
export const SUBEVENT4 = registerKeyword({
  name: "SUBEVENT4",
});
export const SUBEVENT5 = registerKeyword({
  name: "SUBEVENT5",
});
export const SUBEVENT6 = registerKeyword({
  name: "SUBEVENT6",
});
export const SUBEVENT7 = registerKeyword({
  name: "SUBEVENT7",
});
export const SUBEVENT8 = registerKeyword({
  name: "SUBEVENT8",
});
export const SUSPEND = registerKeyword({
  name: "SUSPEND",
  type: KeywordType.Control,
});
export const SUSPSTATUS = registerKeyword({
  name: "SUSPSTATUS",
});
export const SYMBOL = registerKeyword({
  name: "SYMBOL",
});
export const SYMBOLLIST = registerKeyword({
  name: "SYMBOLLIST",
});
export const SYNCHRONOUS = registerKeyword({
  name: "SYNCHRONOUS",
});
export const SYNCLEVEL = registerKeyword({
  name: "SYNCLEVEL",
});
export const SYNCONRETURN = registerKeyword({
  name: "SYNCONRETURN",
});
export const SYNCPOINT = registerKeyword({
  name: "SYNCPOINT",
  type: KeywordType.Control,
});
export const SYSID = registerKeyword({
  name: "SYSID",
});
export const TABLES = registerKeyword({
  name: "TABLES",
});
export const TASKPRIORITY = registerKeyword({
  name: "TASKPRIORITY",
});
export const TCPIP = registerKeyword({
  name: "TCPIP",
  type: KeywordType.Control,
});
export const TCPIPSERVICE = registerKeyword({
  name: "TCPIPSERVICE",
});
export const TCT = registerKeyword({
  name: "TCT",
  type: KeywordType.Control,
});
export const TCTUA = registerKeyword({
  name: "TCTUA",
});
export const TCTUALENG = registerKeyword({
  name: "TCTUALENG",
});
export const TD = registerKeyword({
  name: "TD",
  type: KeywordType.Control,
});
export const TELLERID = registerKeyword({
  name: "TELLERID",
});
export const TEMPLATE = registerKeyword({
  name: "TEMPLATE",
});
export const TERMCODE = registerKeyword({
  name: "TERMCODE",
});
export const TERMID = registerKeyword({
  name: "TERMID",
});
export const TERMINAL = registerKeyword({
  name: "TERMINAL",
  type: KeywordType.Control,
});
export const TERMPRIORITY = registerKeyword({
  name: "TERMPRIORITY",
});
export const TEST = registerKeyword({
  name: "TEST",
  type: KeywordType.Control,
});
export const TEXTKYBD = registerKeyword({
  name: "TEXTKYBD",
});
export const TEXTLENGTH = registerKeyword({
  name: "TEXTLENGTH",
});
export const TEXTPRINT = registerKeyword({
  name: "TEXTPRINT",
});
export const TIME = registerKeyword({
  name: "TIME",
});
export const TIMEOUT = registerKeyword({
  name: "TIMEOUT",
});
export const TIMER = registerKeyword({
  name: "TIMER",
  type: KeywordType.Control,
});
export const TIMESEP = registerKeyword({
  name: "TIMESEP",
});
export const TNADDR = registerKeyword({
  name: "TNADDR",
});
export const TNIPFAMILY = registerKeyword({
  name: "TNIPFAMILY",
});
export const TNPORT = registerKeyword({
  name: "TNPORT",
});
export const TOACTIVITY = registerKeyword({
  name: "TOACTIVITY",
});
export const TOCHANNEL = registerKeyword({
  name: "TOCHANNEL",
});
export const TOCONTAINER = registerKeyword({
  name: "TOCONTAINER",
});
export const TOFLENGTH = registerKeyword({
  name: "TOFLENGTH",
});
export const TOKEN = registerKeyword({
  name: "TOKEN",
  type: KeywordType.Control,
});
export const TOKENLEN = registerKeyword({
  name: "TOKENLEN",
});
export const TOKENTYPE = registerKeyword({
  name: "TOKENTYPE",
});
export const TOLENGTH = registerKeyword({
  name: "TOLENGTH",
});
export const TOPROCESS = registerKeyword({
  name: "TOPROCESS",
});
export const TRACE = registerKeyword({
  name: "TRACE",
});
export const TRACENUM = registerKeyword({
  name: "TRACENUM",
  type: KeywordType.Control,
});
export const TRAILER = registerKeyword({
  name: "TRAILER",
});
export const TRANPRIORITY = registerKeyword({
  name: "TRANPRIORITY",
});
export const TRANSACTION = registerKeyword({
  name: "TRANSACTION",
  type: KeywordType.Control,
});
export const TRANSFORM = registerKeyword({
  name: "TRANSFORM",
  type: KeywordType.Control,
});
export const TRANSFORMER = registerKeyword({
  name: "TRANSFORMER",
});
export const TRANSID = registerKeyword({
  name: "TRANSID",
  type: KeywordType.Control,
});
export const TRIGGER = registerKeyword({
  name: "TRIGGER",
});
export const TRT = registerKeyword({
  name: "TRT",
});
export const TS = registerKeyword({
  name: "TS",
  type: KeywordType.Control,
});
export const TWA = registerKeyword({
  name: "TWA",
});
export const TWALENG = registerKeyword({
  name: "TWALENG",
});
export const TYPENAME = registerKeyword({
  name: "TYPENAME",
});
export const TYPENAMELEN = registerKeyword({
  name: "TYPENAMELEN",
});
export const TYPENS = registerKeyword({
  name: "TYPENS",
});
export const TYPENSLEN = registerKeyword({
  name: "TYPENSLEN",
});
export const UNATTEND = registerKeyword({
  name: "UNATTEND",
});
export const UNCOMMITTED = registerKeyword({
  name: "UNCOMMITTED",
});
export const UNESCAPED = registerKeyword({
  name: "UNESCAPED",
});
export const UNLOCK = registerKeyword({
  name: "UNLOCK",
  type: KeywordType.Control,
});
export const UOW = registerKeyword({
  name: "UOW",
});
export const URI = registerKeyword({
  name: "URI",
});
export const URIMAP = registerKeyword({
  name: "URIMAP",
});
export const URL = registerKeyword({
  name: "URL",
  type: KeywordType.Control,
});
export const URLLENGTH = registerKeyword({
  name: "URLLENGTH",
});
export const USERDATAKEY = registerKeyword({
  name: "USERDATAKEY",
});
export const USERID = registerKeyword({
  name: "USERID",
});
export const USERNAME = registerKeyword({
  name: "USERNAME",
});
export const USERNAMELEN = registerKeyword({
  name: "USERNAMELEN",
});
export const USERPRIORITY = registerKeyword({
  name: "USERPRIORITY",
});
export const USING = registerKeyword({
  name: "USING",
});
export const VALIDATION = registerKeyword({
  name: "VALIDATION",
});
export const VALUELENGTH = registerKeyword({
  name: "VALUELENGTH",
});
export const VERIFY = registerKeyword({
  name: "VERIFY",
  type: KeywordType.Control,
});
export const VERSIONLEN = registerKeyword({
  name: "VERSIONLEN",
});
export const VOLUME = registerKeyword({
  name: "VOLUME",
});
export const VOLUMELENG = registerKeyword({
  name: "VOLUMELENG",
});
export const WAITCICS = registerKeyword({
  name: "WAITCICS",
  type: KeywordType.Control,
});
export const WEB = registerKeyword({
  name: "WEB",
  type: KeywordType.Control,
});
export const WEBSERVICE = registerKeyword({
  name: "WEBSERVICE",
  type: KeywordType.Control,
});
export const WPMEDIA1 = registerKeyword({
  name: "WPMEDIA1",
});
export const WPMEDIA2 = registerKeyword({
  name: "WPMEDIA2",
});
export const WPMEDIA3 = registerKeyword({
  name: "WPMEDIA3",
});
export const WPMEDIA4 = registerKeyword({
  name: "WPMEDIA4",
});
export const WRAP = registerKeyword({
  name: "WRAP",
});
export const WRITEQ = registerKeyword({
  name: "WRITEQ",
  type: KeywordType.Control,
});
export const WSACONTEXT = registerKeyword({
  name: "WSACONTEXT",
  type: KeywordType.Control,
});
export const WSAEPR = registerKeyword({
  name: "WSAEPR",
  type: KeywordType.Control,
});
export const XCTL = registerKeyword({
  name: "XCTL",
  type: KeywordType.Control,
});
export const XMLCONTAINER = registerKeyword({
  name: "XMLCONTAINER",
});
export const XMLTODATA = registerKeyword({
  name: "XMLTODATA",
  type: KeywordType.Control,
});
export const XMLTRANSFORM = registerKeyword({
  name: "XMLTRANSFORM",
});
export const XRBA = registerKeyword({
  name: "XRBA",
});
export const YEAR = registerKeyword({
  name: "YEAR",
});
export const YYDDD = registerKeyword({
  name: "YYDDD",
});
export const YYDDMM = registerKeyword({
  name: "YYDDMM",
});
export const YYMMDD = registerKeyword({
  name: "YYMMDD",
});
export const YYYYDDD = registerKeyword({
  name: "YYYYDDD",
});
export const YYYYDDMM = registerKeyword({
  name: "YYYYDDMM",
});
export const YYYYMMDD = registerKeyword({
  name: "YYYYMMDD",
});
