packages:
  - 'packages/*'
allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
minimumReleaseAgeExclude:
  - monaco-languageclient@11.0.0-next.1
  - vite@8.1.5
  - vscode-ws-jsonrpc@4.0.0-next.1
