DECLARE TEST123
TABLE(JSON_DATA BLOB(256K) NOT NULL);
---
UPDATE DSN8C10.EMP
SET SALARY = SALARY + 100.
WHERE WORKDEPT = 'D11'
---
DECLARE :A VARIABLE FOR BIT DATA
---
declare dummy-cu cursor for
select 'Y' from table t1
inner join table t2 ON t1.key = t2.KEY
inner join table t3 ON t3.key = t1.key
---
ALTER DATABASE ABCDE BUFFERPOOL BP2
INDEXBP BP2 STOGROUP stgrp CCSID 5348
---
ALTER SPECIFIC FUNCTION ENGLES.FOCUS1
WLM ENVIRONMENT WLMENVNAME2
---
ALTER FUNCTION ENGLES.CENTER (CHAR(25), DEC(5,2),
INTEGER) RETURNS NULL ON NULL INPUT
---
alter FUNCTION CENTER (INTEGER, FLOAT)
EXTERNAL NAME 'MIDDLE'
LANGUAGE C
PARAMETER STYLE SQL
WLM ENVIRONMENT (env, *)
CARDINALITY 3
---
ALTER FUNCTION MY_UDF1 DETERMINISTIC
---
ALTER FUNCTION REVERSE
ALTER ACTIVE VERSION
NOT DETERMINISTIC
ALLOW DEBUG MODE
---
ALTER FUNCTION REVERSE(INSTR VARCHAR(4000))
ACTIVATE VERSION V3
---
ALTER FUNCTION REVERSE(INSTR VARCHAR(4000))
REGENERATE ACTIVE VERSION
---
ALTER FUNCTION GET_TABLE
RESTRICT CARDINALITY 10000
---
ALTER FUNCTION MY_UDF1
DETERMINISTIC
---
ALTER INDEX DSN8C10.XEMP1
CLOSE NO
---
ALTER INDEX DSN8C10.XPROJ1
BUFFERPOOL BP1
COPY YES
PIECESIZE 8M
---
ALTER INDEX X1
NOT PADDED
---
ALTER INDEX DSN8C10.XDEPT1
BUFFERPOOL BP1
CLOSE YES
COPY YES
USING VCAT CATLGG
FREEPAGE 6
PCTFREE 11
GBPCACHE ALL
ALTER PARTITION 3
USING VCAT CATLGG
FREEPAGE 13
PCTFREE 13,
ALTER PARTITION 4
USING VCAT CATLGG
GBPCACHE CHANGED,
ALTER PARTITION 5
USING VCAT CATLGG
FREEPAGE 25
PCTFREE 25
---
ALTER INDEX inxnm
BUFFERPOOL sdjks
ADD COLUMN (col1 ASC)
ALTER PARTITION 2 ENDING (MAXVALUE) INCLUSIVE DSSIZE 3G,
ALTER PARTITION 4 ENDING (MINVALUE) INCLUSIVE DSSIZE 3G
---
ALTER MASK M1 ENABLE
---
ALTER MASK M1 REGENERATE
---
ALTER PERMISSION P1 ENABLE
---
ALTER PERMISSION P1 REGENERATE
---
ALTER PROCEDURE SYSPROC.MYPROC WLM ENVIRONMENT PARTSEC
---
ALTER PROCEDURE UPDATE_SALARY_1
ALTER ACTIVE VERSION
NOT DETERMINISTIC
CALLED ON NULL INPUT
ALLOW DEBUG MODE
ASUTIME LIMIT 10
---
ALTER PROCEDURE UPDATE_SALARY_1
ACTIVATE VERSION V3
---
ALTER PROCEDURE UPDATE_SALARY_1
REGENERATE ACTIVE VERSION
---
ALTER SEQUENCE org_seq RESTART
---
ALTER STOGROUP DSN8G120
ADD VOLUMES (DSNV04, DSNV05)
---
ALTER STOGROUP DSN8G120
REMOVE VOLUMES (DSNV04,DSNV05)
---
ALTER STOGROUP DSN8G120
NO KEY LABEL
---
ALTER TABLE DSN8C10.DEPT
ALTER COLUMN DEPTNAME SET DATA TYPE VARCHAR(50)
ADD BLDG CHAR(3) FOR SBCS DATA
---
ALTER TABLE DSN8C10.DEPT
VALIDPROC DSN8EAEM
---
ALTER TABLE DSN8C10.DEPT
VALIDPROC NULL
---
ALTER TABLE DSN8C10.DEPT
FOREIGN KEY(ADMRDEPT) REFERENCES DSN8C10.DEPT
ON DELETE CASCADE
---
ALTER TABLE DSN8C10.DEPT
ADD CHECK (SALARY >= 10000)
---
ALTER TABLE PRODINFO
FOREIGN KEY (PRODNAME,PRODVERNO)
REFERENCES PRODVER_1 (VERNAME,RELNO) ON DELETE RESTRICT
---
ALTER TABLE DSN8C10.DEPT
ADD CONSTRAINT KEY_DEPTNAME UNIQUE( DEPTNAME )
---
ALTER TABLE TRANSCOUNT ADD MATERIALIZED QUERY
(SELECT ACCTID, LOCID, YEAR, COUNT(*) as cnt
FROM TRANS
GROUP BY ACCTID, LOCID, YEAR )
DATA INITIALLY DEFERRED
REFRESH DEFERRED
MAINTAINED BY USER
---
ALTER TABLE TB1
ALTER COLUMN COL1
SET DATA TYPE BINARY(6)
---
ALTER TABLE DSN8C10.EMP
KEY LABEL SECUREKEY01
---
alter TABLE DSN8C10.DEPT ADD PARTITION BY
(col asc, col2 desc) (PARTITION 3 ending (MAXVALUE))
---
alter TABLE DSN8C10.DEPT add column abc 'xyz.join'
---
ALTER TABLE DSN8C10.DEPT
ADD CONSTRAINT CHK_DEPT_DEPTNO
CHECK (DEPTNO BETWEEN 'A00' AND 'Z99')
---
alter TABLE DSN8C10.DEPT
CONSTRAINT xyz
UNIQUE (col1, BUSINESS_TIME WITHOUT OVERLAPS)
---
alter TABLE DSN8C10.DEPT
ALTER PARTITIONING TO PARTITION BY range (col1 desc)
(PARTITION 3 ending (MAXVALUE))
---
alter TABLE DSN8C10.DEPT
ALTER PARTITION 3 ending (MAXVALUE)
---
ALTER TABLESPACE DSN8D12A.DSN8S12D
BUFFERPOOL BP2
LOCKSIZE PAGE
---
ALTER TABLESPACE DSN8D12A.DSN8S12E
CLOSE NO
SECQTY -1
ALTER PARTITION 1 PCTFREE 20
---
ALTER TABLESPACE TS01DB.TS01TS
MAXPARTITIONS 30
---
ALTER TRIGGER TRIGGER1
SECURED
---
ALTER TRIGGER TRIGGER1
ALTER ALLOW DEBUG MODE
---
ALTER TRIGGER TRIGGER1
ACTIVATE VERSION V3
---
ALTER TRIGGER TRIGGER1
REGENERATE ACTIVE VERSION
---
ALTER TRUSTED CONTEXT CTX1
ALTER DEFAULT ROLE CTXROLE2
---
ALTER TRUSTED CONTEXT CTX3
ALTER DISABLE
ADD USE FOR BILL
---
ALTER TRUSTED CONTEXT CTX4
REPLACE USE FOR JOE WITHOUT AUTHENTICATION
ADD USE FOR PUBLIC WITH AUTHENTICATION,
TOM ROLE SPLROLE
---
ALTER TRUSTED CONTEXT REMOTECTX
ALTER ATTRIBUTES (ADDRESS "9.12.155.200",
ENCRYPTION "LOW")
---
ALTER TRUSTED CONTEXT CTX1
drop
ATTRIBUTES (
ADDRESS "huu",
SERVAUTH "JOB989L"
)
---
alter TRUSTED CONTEXT CTX1
add
ATTRIBUTES (
address "2 . 4 . 5 . 62",
SERVAUTH "23"
)
---
ALTER VIEW MYVIEW REGENERATE
---
ALTER TRUSTED CONTEXT REMOTECTX
ALTER ATTRIBUTES (ADDRESS "9.12.155.200",
ENCRYPTION "LOW")
---
CREATE ALIAS LATABLES FOR DB2USCALABOA5281.SYSIBM.SYSTABLES
---
CREATE AUX TABLE EMP_PHOTO_ATAB
IN DSN8D12A.PHOTOLTS
STORES DSN8C10.EMP
COLUMN EMP_PHOTO
---
CREATE DATABASE DSN8D12P
STOGROUP DSN8G120
BUFFERPOOL BP8K1
INDEXBP BP2
---
CREATE DATABASE DSN8TEMP
CCSID ASCII
---
CREATE FUNCTION NTEST1 (SMALLINT)
   RETURNS SMALLINT
   EXTERNAL NAME 'NTESTMOD'
   SPECIFIC MINENULL1
   LANGUAGE C
    DETERMINISTIC
    NO SQL
    FENCED
    PARAMETER STYLE SQL
    RETURNS NULL ON NULL INPUT
    NO EXTERNAL ACTION
---
CREATE FUNCTION REVERSE(INSTR VARCHAR(4000))
RETURNS VARCHAR(4000)
return null
---
CREATE FUNCTION CENTER (INTEGER, FLOAT)
RETURNS FLOAT
EXTERNAL NAME 'MIDDLE'
LANGUAGE C
DETERMINISTIC
NO SQL
FENCED
PARAMETER STYLE SQL
NO EXTERNAL ACTION
STAY RESIDENT YES
---
CREATE FUNCTION SMITH.CENTER (FLOAT, FLOAT, FLOAT)
    RETURNS DECIMAL(8,4) CAST FROM FLOAT
    EXTERNAL NAME 'CMOD'
    SPECIFIC FOCUS98
    LANGUAGE C
    DETERMINISTIC
    NO SQL
    FENCED
    PARAMETER STYLE SQL
    NO EXTERNAL ACTION
    SCRATCHPAD
    NO FINAL CALL
---
CREATE FUNCTION FINDV (CLOB(100K))
    RETURNS INTEGER
    FENCED
    LANGUAGE JAVA
    PARAMETER STYLE JAVA
    EXTERNAL NAME 'JAVAUDFS.FINDVWL'
    NO EXTERNAL ACTION
    CALLED ON NULL INPUT
    DETERMINISTIC
    NO SQL
---
CREATE FUNCTION CENTER (INTEGER, FLOAT)
RETURNS FLOAT
EXTERNAL NAME 'MIDDLE'
LANGUAGE C
PARAMETER STYLE SQL
WLM ENVIRONMENT (env, *)
---
CREATE FUNCTION CENTER (INTEGER, FLOAT)
RETURNS FLOAT
EXTERNAL NAME 'MIDDLE'
LANGUAGE C
PARAMETER STYLE SQL
WLM ENVIRONMENT env
CARDINALITY 3
---
CREATE FUNCTION DOCMATCH (VARCHAR(30), VARCHAR(255))
                             RETURNS TABLE (DOC_ID CHAR(16))
 EXTERNAL NAME ABC
 LANGUAGE C
 PARAMETER STYLE SQL
 NO SQL
 DETERMINISTIC
 NO EXTERNAL ACTION
 FENCED
 SCRATCHPAD
 FINAL CALL
 DISALLOW PARALLEL
 CARDINALITY 20
---
CREATE FUNCTION tf6(p1 VARCHAR(10))
RETURNS GENERIC TABLE
EXTERNAL NAME 'tf6'
LANGUAGE C
PARAMETER STYLE SQL
DETERMINISTIC
NO EXTERNAL ACTION
FENCED
SCRATCHPAD
FINAL CALL
---
CREATE FUNCTION TAN (X DOUBLE)
RETURNS DOUBLE
LANGUAGE SQL
CONTAINS SQL
NO EXTERNAL ACTION
DETERMINISTIC
RETURN SIN(X)/COS(X)
---
CREATE FUNCTION AVE (HATSIZE) RETURNS HATSIZE
SOURCE SYSIBM.AVG (INTEGER)
---
CREATE FUNCTION MYCENTER (INTEGER, INTEGER)
RETURNS FLOAT
SOURCE SMITH.CENTER (INTEGER, FLOAT)
---
CREATE GLOBAL TEMPORARY TABLE CURRENTMAP
  (CODE INTEGER NOT NULL, MEANING VARCHAR(254) NOT NULL)
---
CREATE GLOBAL TEMPORARY TABLE EMP
    (TMPDEPTNO   CHAR(3)     NOT NULL,
    TMPDEPTNAME VARCHAR(36) NOT NULL,
    TMPMGRNO    CHAR(6)  ,
    TMPLOCATION CHAR(16))
---
CREATE UNIQUE INDEX DSN8C10.XDEPT1
    ON DSN8C10.DEPT
    (DEPTNO ASC)
    PADDED
    USING STOGROUP DSN8G120
    PRIQTY 512
    SECQTY 64
    ERASE NO
    BUFFERPOOL BP1
    CLOSE YES
    PIECESIZE 1M
---
CREATE INDEX DSN8C10.XEMP2
    ON DSN8C10.EMP
    (EMPNO ASC)
    USING STOGROUP DSN8G120
    PRIQTY 36
    ERASE NO
    CLUSTER
    PARTITION BY RANGE
    (PARTITION 1 ENDING AT("H99"),
    PARTITION 2 ENDING AT("P99"),
    PARTITION 3 ENDING AT("Z99"),
    PARTITION 4 ENDING AT("999"))
    BUFFERPOOL BP1
    CLOSE YES
    COPY YES
---
CREATE UNIQUE INDEX DSN8C10.XDEPT1
ON DSN8C10.DEPT
(DEPTNO ASC)
USING VCAT DSNCAT
PIECESIZE 1048576K
---
CREATE UNIQUE INDEX DSN8C10.XPHOTO
    ON DSN8C10.EMP_PHOTO_ATAB
    USING VCAT DSNCAT
    COPY YES
---
create index inxnm on  tabnam (col1 ASC)
cluster
partition by
(partition 2 ending (MAXVALUE) inclusive dssize 3G)
not padded
---
CREATE INDEX idx_customer ON customers(info)
     GENERATE KEY USING XMLPATTERN
"/cust:customer/cust:name" AS SQL VARCHAR(50)
---
CREATE INDEX CSTPHNX2 ON CUST(XMLCUST)
GENERATE KEY USING XMLPATTERN
"declare namespace s='http://example.com/ns';"
AS SQL VARCHAR(12)
---
CREATE LOB TABLESPACE PHOTOLTS
    IN DSN8D12A
    USING STOGROUP DSN8G120
         PRIQTY 3200
         SECQTY 1600
     LOCKSIZE LOB
     BUFFERPOOL BP16K0
     GBPCACHE SYSTEM
     NOT LOGGED
     CLOSE NO
---
CREATE MASK SSN_MASK ON EMPLOYEE
   FOR COLUMN SSN RETURN
     CASE
          WHEN (VERIFY_GROUP_FOR_USER
          (SESSION_USER,'PAYROLL') = 1)
                 THEN SSN
          WHEN (
          VERIFY_GROUP_FOR_USER(SESSION_USER,'MGR') = 1)
           THEN 'XXX-XX-' || SUBSTR(SSN,8,4)
          ELSE NULL
     END
   ENABLE;

COMMIT;

ALTER TABLE EMPLOYEE
    ACTIVATE COLUMN ACCESS CONTROL;

COMMIT;

SELECT SSN FROM EMPLOYEE
    WHERE EMPNO = 123456
---
CREATE MASK SSN_MASK ON EMPLOYEE
    FOR COLUMN SSN RETURN
      CASE
           WHEN (1 = 1)
            THEN 'XXX-XX-' || SUBSTR(SSN,8,4)
           ELSE NULL
      END
    ENABLE;

COMMIT;

ALTER TABLE EMPLOYEE
    ACTIVATE COLUMN ACCESS CONTROL;

COMMIT;

SELECT 'XXX-XX-' ||
 SUBSTR(SSN,8,4) FROM EMPLOYEE
    WHERE EMPNO = 123456
---
CREATE MASK CITY_MASK ON LIBRARY_USAGE
    FOR COLUMN CITY RETURN
      CASE
           WHEN (LIBRARY_OPT = 'OPT-IN')
            THEN CITY
           ELSE ' '
      END
    ENABLE;

COMMIT;

ALTER TABLE LIBRARY_USAGE
   ACTIVATE COLUMN ACCESS CONTROL;

COMMIT;

SELECT CITY, AVG(LIBRARY_TIME) FROM LIBRARY_USAGE
   GROUP BY CITY
---
CREATE MASK SALARY_MASK ON EMPLOYEE
   FOR COLUMN SALARY RETURN
       CASE
            WHEN (BONUS < 10000)
             THEN SALARY
            ELSE NULL
       END
   ENABLE;

COMMIT;

CREATE MASK BONUS_MASK ON EMPLOYEE
   FOR COLUMN BONUS RETURN
       CASE
            WHEN (BONUS > 5000)
             THEN NULL
            ELSE BONUS
       END
   ENABLE;

COMMIT;

ALTER TABLE EMPLOYEE
    ACTIVATE COLUMN ACCESS CONTROL;

COMMIT;

SELECT SALARY FROM EMPLOYEE
    WHERE EMPNO = 123456
---
CREATE TABLE EMPLOYEE (EMPID INT,
                 DEPTID CHAR(8),
                 SALARY DEC(9,2) NOT NULL,
                 BONUS DEC(9,2));

CREATE MASK SALARY_MASK ON EMPLOYEE
    FOR COLUMN SALARY RETURN
       CASE
            WHEN SALARY < 10000
             THEN CAST(SALARY*2 AS DEC(9,2))
            ELSE COALESCE(CAST(SALARY/2
            AS DEC(9,2)), BONUS)
       END
    ENABLE;

COMMIT;

CREATE MASK BONUS_MASK ON EMPLOYEE
    FOR COLUMN BONUS RETURN
      CASE
          WHEN BONUS > 1000
           THEN BONUS
          ELSE NULL
      END
    ENABLE;

COMMIT;

ALTER TABLE EMPLOYEE
    ACTIVATE COLUMN ACCESS CONTROL;

COMMIT;

SELECT SALARY FROM DEPT
    LEFT JOIN EMPLOYEE ON DEPTNO = DEPTID;


SELECT CASE WHEN SALARY IS NULL THEN NULL
            WHEN SALARY < 10000 THEN
            CAST(SALARY*2 AS DEC(9,2))
            ELSE COALESCE(CAST(SALARY/2 AS DEC(9,2)),
            BONUS)
       END SALARY
       FROM DEPT
         LEFT JOIN EMPLOYEE ON DEPTNO = DEPTID
---
CREATE PERMISSION SALARY_ROW_ACCESS ON EMPLOYEE
   FOR ROWS WHERE VERIFY_GROUP_FOR_USER
 (SESSION_USER,'MGR','ACCOUNTING') = 1
            AND
            ACCOUNTING_UDF(SALARY) < 120000
   ENFORCED FOR ALL ACCESS
   ENABLE;

COMMIT;

ALTER TABLE EMPLOYEE
    ACTIVATE ROW ACCESS CONTROL;

COMMIT;

SELECT SALARY FROM EMPLOYEE
   WHERE EMPNO = 123456
---
CREATE PERMISSION TELLER_ROW_ACCESS ON CUSTOMER
   FOR ROWS WHERE VERIFY_GROUP_FOR_USER
     (SESSION_USER,'TELLER') = 1
            AND
    BRANCH = (SELECT HOME_BRANCH FROM INTERNAL_INFO
          WHERE EMP_ID = SESSION_USER)
    ENFORCED FOR ALL ACCESS
    ENABLE;

COMMIT;

CREATE PERMISSION CSR_ROW_ACCESS ON CUSTOMER
   FOR ROWS WHERE
     VERIFY_GROUP_FOR_USER(SESSION_USER,'CSR') = 1
   ENFORCED FOR ALL ACCESS
   ENABLE;

COMMIT;

ALTER TABLE CUSTOMER
   ACTIVATE ROW ACCESS CONTROL;

COMMIT;

SELECT * FROM CUSTOMER
---
CREATE PROCEDURE SYSPROC.MYPROC(IN INT, OUT INT,
   OUT DECIMAL(7,2))
         LANGUAGE COBOL
         EXTERNAL NAME MYMODULE
         PARAMETER STYLE GENERAL
         WLM ENVIRONMENT PARTSA
         DYNAMIC RESULT SETS 1
---
CREATE PROCEDURE
SYSPROC.MYPROC(IN INT, OUT INT, OUT DECIMAL(7,2))
    LANGUAGE COBOL
    EXTERNAL NAME MYMODULE
    PARAMETER STYLE SQL
    WLM ENVIRONMENT PARTSA
    DYNAMIC RESULT SETS 1
    RUN OPTIONS
"HEAP(,,ANY),BELOW(4K,,),ALL31(ON),STACK(,,ANY,)"
---
CREATE PROCEDURE PARTS_ON_HAND(IN PARTNUM INT,
         OUT COST DECIMAL(7,2),
         OUT QUANTITY INT)
         LANGUAGE JAVA
         EXTERNAL NAME 'PARTS.ONHAND'
         PARAMETER STYLE JAVA
---
CREATE PROCEDURE UPDATE_SALARY_1
 (IN EMPLOYEE_NUMBER CHAR(10),
 IN RATE DECIMAL(6,2))
 LANGUAGE SQL
 MODIFIES SQL DATA
  UPDATE EMP
  SET SALARY = SALARY * RATE
  WHERE EMPNO = EMPLOYEE_NUMBER
---
CREATE PROCEDURE UPDATE_SALARY_1
 (IN EMPLOYEE_NUMBER CHAR(10),
 IN RATE DECIMAL(6,2))
 LANGUAGE SQL
 MODIFIES SQL DATA
 DETERMINISTIC
 COMMIT ON RETURN YES
   UPDATE EMP
   SET SALARY = SALARY * RATE
   WHERE EMPNO = EMPLOYEE_NUMBER
---
CREATE ROLE TELLER
---
CREATE SEQUENCE ORDER_SEQ
START WITH 1
INCREMENT BY 1
NO MAXVALUE
NO CYCLE
CACHE 24
---
CREATE SEQUENCE ORDER_SEQ
      START WITH 1
      INCREMENT BY 1
      NO MAXVALUE
      NO CYCLE
      CACHE 20;
     INSERT INTO ORDERS (ORDERNO, CUSTNO)
       VALUES (NEXT VALUE FOR ORDER_SEQ, 123456)
---
CREATE STOGROUP DSN8G120
     VOLUMES (ABC005,DEF008)
     VCAT DSNCAT
---
CREATE STOGROUP DSNCG100
     VOLUMES (ABC001,DEF003) VCAT DSNCAT
     KEY LABEL STG01KLABEL
---
create STOGROUP DSNCG100
  VOLUMES ('*','*') VCAT DSNCAT
  DATACLAS taco
---
create STOGROUP DSNCG100
    VOLUMES ('*','*') VCAT DSNCAT
    NO KEY LABEL
    DATACLAS taco
---
CREATE TABLE DSN8C10.DEPT
     (DEPTNO   CHAR(3)     NOT NULL,
      DEPTNAME VARCHAR(36) NOT NULL,
      MGRNO    CHAR(6)             ,
      ADMRDEPT CHAR(3)     NOT NULL,
      LOCATION CHAR(16)            ,
      PRIMARY KEY(DEPTNO)          )
     IN DSN8D12A.DSN8S12D
---
CREATE TABLE DSN8C10.PROJ
     (PROJNO   CHAR(6)      NOT NULL,
      PROJNAME VARCHAR(24)  NOT NULL,
      DEPTNO   CHAR(3)      NOT NULL,
      RESPEMP  CHAR(6)      NOT NULL,
      PRSTAFF  DECIMAL(5,2)         ,
      PRSTDATE DATE                 ,
      PRENDATE DATE                 ,
      MAJPROJ  CHAR(6)      NOT NULL)
     IN DATABASE DSN8D12A
     VALIDPROC DSN8EAPR
---
CREATE TABLE ACTIVITY
     (PROJNO   CHAR(6)      NOT NULL,
      ACTNO    SMALLINT     NOT NULL,
      ACTDEPT  CHAR(3)      NOT NULL,
      ACTOWNER CHAR(6)      NOT NULL,
      ACSTAFF  DECIMAL(5,2)         ,
      ACSTDATE DATE         NOT NULL,
      ACENDATE DATE                 ,
      FOREIGN KEY (ACTDEPT,ACTOWNER) REFERENCES
      PROJECT (DEPTNO,RESPEMP) ON DELETE RESTRICT)
     IN DSN8D12A.DSN8S12D
---
CREATE TABLE DSN8C10.EMP_PHOTO_RESUME (
  EMPNO      CHAR(6)     NOT NULL,
  EMP_ROWID  ROWID NOT NULL GENERATED ALWAYS,
  EMP_PHOTO  BLOB(110K),
  RESUME     CLOB(5K),
  PRIMARY KEY (EMPNO)
)
     IN DSN8D12A.DSN8S12E
     CCSID EBCDIC
---
CREATE TABLE EMPLOYEE
     (EMPNO      INTEGER GENERATED ALWAYS AS IDENTITY,
      ID         SMALLINT,
      NAME       CHAR(30),
      SALARY     DECIMAL(5,2),
      DEPTNO     SMALLINT)
     IN DSN8D12A.DSN8S12D
---
CREATE TABLE STRANS AS
     (SELECT YEAR AS SYEAR, MONTH AS SMONTH,
      DAY AS SDAY, SUM(AMOUNT) AS SSUM
      FROM TRANS
      GROUP BY YEAR, MONTH, DAY)
      DATA INITIALLY DEFERRED REFRESH DEFERRED
---
CREATE TABLE TS01TB
       (C1 SMALLINT,
        C2 DECIMAL(9,2),
        C3 CHAR(4))
    APPEND YES
    IN TS01DB.TS01TS
---
CREATE TABLE TS02TB
       (C1 SMALLINT,
        C2 DECIMAL(9,2),
        C3 CHAR(4))
     PARTITION BY SIZE EVERY 4G
     IN DATABASE DSNDB04
---
CREATE TABLE EMP_INFO
       (EMPNO CHAR(6) NOT NULL,
        EMP_INFOCHANGE NOT NULL
           GENERATED ALWAYS FOR EACH ROW ON UPDATE
           AS ROW CHANGE TIMESTAMP,
        EMP_ADDRESS VARCHAR(300),
        EMP_PHONENO CHAR(4),
        PRIMARY KEY (EMPNO))
---
CREATE TABLE TB01 (
   ACCT_NUM         INTEGER,
   CUST_LAST_NM     CHAR(15),
   LAST_ACTIVITY_DT VARCHAR(25),
   COL2             CHAR(10),
   COL3             CHAR(25),
   COL4             CHAR(25),
   COL5             CHAR(25),
   COL6             CHAR(55),
   STATE            CHAR(55))
 IN DBB.TS01

  PARTITION BY (ACCT_NUM)
   (PARTITION 1 ENDING AT (199),
    PARTITION 2 ENDING AT (299),
    PARTITION 3 ENDING AT (399),
    PARTITION 4 ENDING AT (MAXVALUE))
---
CREATE TABLESPACE DSN8S12D
     IN DSN8D12A
     USING STOGROUP DSN8G120
       PRIQTY 52
       SECQTY 20
       ERASE NO
     LOCKSIZE PAGE
     BUFFERPOOL BP1
     CLOSE YES
---
CREATE TABLESPACE SALESHX
     IN DSN8D12A
     USING STOGROUP DSN8G120
       PRIQTY 4000
       SECQTY 130
       ERASE NO
     NUMPARTS 82
     (PARTITION 80
       COMPRESS YES,
      PARTITION 81
       COMPRESS YES,
      PARTITION 82
       COMPRESS YES
       ERASE YES)
     LOCKSIZE PAGE
     BUFFERPOOL BP1
     CLOSE NO
---
CREATE TABLESPACE TS1
     IN DSN8D12A
     USING STOGROUP DSN8G120
     NUMPARTS 55
     SEGSIZE 16
     LOCKSIZE ANY
---
CREATE TABLESPACE TS2
     IN DSN8D12A
     USING STOGROUP DSN8G120
     NUMPARTS 7
     (
      PARTITION 1 COMPRESS YES,
      PARTITION 3 COMPRESS YES,
      PARTITION 5 COMPRESS YES,
      PARTITION 7 COMPRESS YES
     )
     SEGSIZE 64
     DEFINE NO
---
create tablespace amsm lockmax 23 define yes member
cluster dssize 23G TRACKMOD YES
compress yes huffman lockpart yes
numparts 2 (partition 2 using STOGROUP stgname PRIQTY -1)
---
CREATE TRIGGER NEW_HIRE
      AFTER INSERT ON EMPLOYEE
      FOR EACH ROW
      BEGIN ATOMIC
        UPDATE COMPANY_STATS SET NBEMP = NBEMP + 1;
      END
---
CREATE TRIGGER REORDER
     AFTER UPDATE OF ON_HAND, MAX_STOCKED ON PARTS
     REFERENCING NEW AS NROW
     FOR EACH ROW
     WHEN (NROW.ON_HAND < 0.10 * NROW.MAX_STOCKED)
     BEGIN ATOMIC
       insert into tab (QTY_ORDERED)
       VALUES(ISSUE_SHIP_REQUEST(NROW.MAX_STOCKED
       - NROW.ON_HAND, NROW.PARTNO));
     END
---
CREATE TRIGGER REORDER
     AFTER UPDATE OF ON_HAND, MAX_STOCKED ON PARTS
     REFERENCING NEW_TABLE AS NTABLE
     FOR EACH STATEMENT
       BEGIN ATOMIC
         SELECT ISSUE_SHIP_REQUEST(MAX_STOCKED -
            ON_HAND, PARTNO)
           FROM NTABLE
         WHERE (ON_HAND < 0.10 * MAX_STOCKED);
     END
---
CREATE TRIGGER SAL_ADJ
     AFTER UPDATE OF SALARY ON EMPLOYEE
     REFERENCING OLD AS OLD_EMP
                 NEW AS NEW_EMP
     FOR EACH ROW
     WHEN (NEW_EMP.SALARY > (OLD_EMP.SALARY * 1.20))
       BEGIN ATOMIC
         SIGNAL SQLSTATE '75001'
         ('Invalid Salary Increase - Exceeds 20');
       END
---
CREATE TABLE WEATHER
      (CITY VARCHAR(25),
       TEMPF DECIMAL(5,2));
   CREATE VIEW CELSIUS_WEATHER (CITY, TEMPC) AS
      SELECT CITY, (TEMPF-32)/1.8
      FROM WEATHER
---
create TRIGGER salary_update_trigger
AFTER UPDATE OF salary ON employees
REFERENCING NEW AS n OLD AS o
FOR EACH ROW
WHEN (n.salary > 1.1 * o.salary)
BEGIN ATOMIC
INSERT INTO salary_audit (emp_id)
VALUES ((n.emp_id));
INSERT INTO salary_audit (emp_id, name)
VALUES (n.emp_id, kkl);
END
---
CREATE TRUSTED CONTEXT CTX1
       BASED UPON CONNECTION USING SYSTEM AUTHID ADMF001
       ATTRIBUTES (ADDRESS "9.30.131.203",
                   ENCRYPTION "LOW")
       DEFAULT ROLE CTXROLE
       ENABLE
       WITH USE FOR SAM, JOE ROLE ROLE1 WITH AUTHENTICATION
---
CREATE TRUSTED CONTEXT CTX2
     BASED UPON CONNECTION USING SYSTEM AUTHID ADMF002
     ATTRIBUTES (JOBNAME "WASPROD")
     DEFAULT ROLE CTXROLE WITH ROLE AS OBJECT OWNER
     AND QUALIFIER
     ENABLE
     WITH USE FOR SALLY
---
CREATE TRUSTED CONTEXT CTX1
    BASED UPON CONNECTION USING SYSTEM AUTHID ADMF001
    ATTRIBUTES (
    address "2 . 4 . 5 . 62",
    ENCRYPTION "LOW",
    SERVAUTH "23"
    )
    ENABLE NO DEFAULT SECURITY LABEL
    with use for autnm security label sclbl
---
CREATE TYPE PHONENUMBERS AS DECIMAL(10,0) ARRAY[50]
---
CREATE TYPE GENERIC.NUMBERS AS DECFLOAT(34) ARRAY??(??)
---
CREATE TYPE PERSONAL_PHONENUMBERS AS DECIMAL(16,0)
         ARRAY??(VARCHAR(8)??)
---
CREATE TYPE CAPITALSARRAY AS VARCHAR(30)
ARRAY[VARCHAR(20)]
---
CREATE TYPE PRODUCTS AS VARCHAR(40) ARRAY??(INTEGER??)
---
CREATE TYPE SHOESIZE AS INTEGER
---
CREATE TYPE MILES AS DOUBLE
---
CREATE VARIABLE MYSCHEMA.MYJOB_PRINTER VARCHAR(30)
 DEFAULT "Default printer"
---
CREATE VARIABLE SCHEMA1.GV_DEPTNO INTEGER
 DEFAULT "Unassigned"
---
CREATE VIEW DSN8C10.VPROJRE1
     (PROJNO,PROJNAME,PROJDEP,RESPEMP,
      FIRSTNME,MIDINIT,LASTNAME)
     AS SELECT ALL
     PROJNO,PROJNAME,DEPTNO,EMPNO,
     FIRSTNME,MIDINIT,LASTNAME
     FROM DSN8C10.PROJ, DSN8C10.EMP
     WHERE RESPEMP = EMPNO
---
CREATE VIEW DSN8C10.FIRSTQTR (SNO, CHARGES, DATE) AS
  SELECT SNO, CHARGES, DATE
  FROM MONTH1
  WHERE DATE BETWEEN '01/01/2000' and '01/31/2000'
    UNION All
  SELECT SNO, CHARGES, DATE
  FROM MONTH2
  WHERE DATE BETWEEN '02/01/2000' and '02/29/2000'
    UNION All
  SELECT SNO, CHARGES, DATE
  FROM MONTH3
  WHERE DATE BETWEEN '03/01/2000' and '03/31/2000'
---
create VIEW top_publishers AS
WITH publisher_ratings (col) AS (
SELECT
            p.name AS publisher_name,
            AVG(b.rating) AS avg_rating
FROM
    publishers p
    INNER JOIN books b ON p.publisher_id = b.publisher_id
GROUP BY
            p.name
)
SELECT
publisher_name,
avg_rating
FROM
publisher_ratings
WHERE
avg_rating = (SELECT MAX(avg_rating) FROM publisher_ratings)
---
create table all (all integer, avg integer)
---
DECLARE C1 CURSOR FOR
SELECT DEPTNO, DEPTNAME, MGRNO
FROM DSN8C10.DEPT
WHERE ADMRDEPT = 'A00'
---
DECLARE GLOBAL TEMPORARY TABLE SESSION.TEMP_EMP
  (EMPNO     CHAR(6)   NOT NULL,
   SALARY    DECIMAL(9, 2),
   BONUS     DECIMAL(9, 2),
   COMM      DECIMAL(9, 2))
   CCSID EBCDIC
   ON COMMIT PRESERVE ROWS
---
DECLARE DSN8C10.EMP TABLE
 (EMPNO     CHAR(6)     NOT NULL,
  FIRSTNME  VARCHAR(12) NOT NULL,
  MIDINIT   CHAR(1)     NOT NULL,
  LASTNAME  VARCHAR(15) NOT NULL,
  WORKDEPT  CHAR(3)             ,
  PHONENO   CHAR(4)             ,
  HIREDATE  DATE                ,
  JOB       CHAR(8)             ,
  EDLEVEL   SMALLINT            ,
  SEX       CHAR(1)             ,
  BIRTHDATE DATE                ,
  SALARY    DECIMAL(9,2)        ,
  BONUS     DECIMAL(9,2)        ,
  TIMESTAMP TIMESTAMP NOT NULL,
  COMM      DECIMAL(9,2)        )
---
DECLARE OBJECT_STATEMENT STATEMENT
---
DECLARE :FRED VARIABLE CCSID EBCDIC FOR BIT DATA;
DECLARE :JEAN VARIABLE CCSID 1208;
DECLARE :DAVE VARIABLE CCSID UNICODE;
DECLARE :PETE VARIABLE CCSID 1200;
DECLARE :AMBER VARIABLE CCSID UNICODE;
---
declare asasa statement
---
declare asasa statement
---
DECLARE TBL TABLE
 (TIMESTAMP TIMESTAMP(6) WITHOUT TIMEZONE NOT NULL)
---
DESCRIBE CURSOR C1 INTO :HOSTVAR
---
DESCRIBE INPUT STMT1_NAME INTO :HOSTVAR
---
DESCRIBE OUTPUT STMT1_NAME INTO :HOSTVAR USING LABELS
---
DESCRIBE PROCEDURE MyProc INTO :HOSTVAR
---
DESCRIBE TABLE :HOSTVAR INTO :HOSTVAR USING BOTH
---
GRANT CREATE IN COLLECTION DSN8CC91 TO ROLE ROLE1
---
GRANT CREATE IN COLLECTION QAACLONE, DSN8CC61 TO CLARK
---
GRANT DROP
     ON DATABASE DSN8D12A
     TO PEREZ
---
GRANT REPAIR
     ON DATABASE DSN8D12A
     TO PUBLIC
---
GRANT CREATETAB,LOAD
 ON DATABASE DSN8D12A
 TO WALKER,PIANKA,FUJIMOTO
 WITH GRANT OPTION
---
GRANT LOAD
 ON DATABASE DSN9D91A
 TO ROLE ROLE1
---
GRANT EXECUTE ON FUNCTION CALC_SALARY TO JONES
---
GRANT EXECUTE ON PROCEDURE VACATION_ACCR TO PUBLIC
---
GRANT EXECUTE ON SPECIFIC FUNCTION DEPT85_TOT TO ADMIN_A
 WITH GRANT OPTION
---
GRANT COPY ON PACKAGE DSN8CC61.* TO LEWIS
---
GRANT ALL ON PACKAGE CLCT1.PKG1, CLCT2.PKG2 TO JONES
---
GRANT EXECUTE ON PACKAGE DSN9CC13.* TO ROLE ROLE1
---
GRANT BIND ON PLAN DSN8IP12 TO JONES
---
GRANT BIND,EXECUTE ON PLAN DSN8CP12 TO PUBLIC
---
GRANT EXECUTE ON PLAN DSN8CP12 TO ADAMSON,
BROWN WITH GRANT OPTION
---
GRANT BIND ON PLAN DSN91PLN TO ROLE ROLE1
---
GRANT CREATEIN ON SCHEMA T_SCORES TO JONES
---
GRANT ALTERIN ON SCHEMA DEPT TO ADMIN_A
 WITH GRANT OPTION
---
GRANT CREATEIN, ALTERIN,
DROPIN ON SCHEMA NEW_HIRE, PROMO, RESIGN TO HR
---
GRANT ALTERIN ON SCHEMA EMPLOYEE TO ROLE ROLE1
---
GRANT USAGE
ON SEQUENCE MYNUM
TO JONES
---
GRANT USAGE ON SEQUENCE ORDER_SEQ TO ROLE ROLE1
---
GRANT DISPLAY
TO LUTZ
---
GRANT BSDS,RECOVER
TO PARKER,SETRIGHT
WITH GRANT OPTION
---
GRANT TRACE
TO PUBLIC
---
GRANT ARCHIVE TO ROLE ROLE1
---
GRANT CREATE_SECURE_OBJECT
TO STEVE
---
GRANT DBADM ON SYSTEM
 TO ROLE ADMINROLE;
GRANT DBADM, ACCESSCTRL, DATAACCESS
ON SYSTEM
TO SALLY
---
GRANT DBADM WITHOUT ACCESSCTRL
WITHOUT DATAACCESS
ON SYSTEM
TO JOHN
---
GRANT SELECT ON DSN8C10.EMP TO PULASKI
---
GRANT ALL ON TABLE DSN8C10.EMP TO KWAN,
THOMPSON WITH GRANT OPTION
---
GRANT ALTER ON TABLE DSN9910.EMP
TO ROLE ROLE1
---
GRANT USAGE ON TYPE SHOE_SIZE TO JONES
---
GRANT USAGE ON TYPE US_DOLLAR TO PUBLIC
---
GRANT USAGE ON TYPE MILES
TO ROLE ROLE1
---
GRANT READ ON VARIABLE ACCOUNTNO TO JONES
---
GRANT USE OF TABLESPACE
 DSN8D12A.DSN8S12D
 TO PUBLIC
---
GRANT USE OF STOGROUP SG1
TO ROLE ROLE1
---
REVOKE CREATE IN COLLECTION QAACLONE,
DSN8CC61 FROM CLARK
---
REVOKE CREATE IN COLLECTION DSN8CC91 FROM ROLE ROLE1
---
REVOKE DROP
 ON DATABASE DSN8D12A
 FROM PEREZ
---
REVOKE REPAIR
 ON DATABASE DSN8D12A
 FROM PUBLIC
---
REVOKE CREATETAB,LOAD
ON DATABASE DSN8D12A
FROM WALKER,PIANKA,FUJIMOTO
---
REVOKE LOAD
ON DATABASE DSN8D12A
FROM ROLE ROLE1
---
REVOKE EXECUTE ON FUNCTION CALC_SALARY FROM JONES
---
REVOKE EXECUTE ON PROCEDURE VACATION_ACCR FROM PUBLIC
---
REVOKE COPY ON PACKAGE DSN8CC61.* FROM LEWIS
---
REVOKE EXECUTE ON PACKAGE DSN9CC13.* FROM ROLE ROLE1
---
REVOKE BIND ON PLAN DSN8IP12 FROM JONES
---
REVOKE BIND,EXECUTE ON PLAN DSN8CP12 FROM PUBLIC
---
REVOKE EXECUTE ON PLAN DSN8CP12 FROM ADAMSON,BROWN
---
REVOKE BIND ON PLAN DSN91PLN FROM ROLE ROLE1
---
REVOKE CREATEIN ON SCHEMA T_SCORES FROM JONES
---
REVOKE CREATEIN ON SCHEMA VAC FROM PUBLIC
---
REVOKE ALTERIN ON SCHEMA DEPT FROM ADMIN_A
---
REVOKE ALTERIN, DROPIN ON SCHEMA
NEW_HIRE, PROMO, RESIGN FROM HR
---
REVOKE ALTERIN ON SCHEMA EMPLOYEE FROM ROLE ROLE1
---
REVOKE USAGE
 ON SEQUENCE MYNUM
 FROM JONES
---
REVOKE USAGE
ON SEQUENCE ORDER_SEQ
FROM ROLE ROLE1
---
REVOKE DISPLAY
FROM LUTZ
---
REVOKE BSDS,RECOVER
FROM PARKER,SETRIGHT
---
REVOKE TRACE
FROM PUBLIC
---
REVOKE ARCHIVE
 FROM ROLE ROLE1
---
REVOKE CREATE_SECURE_OBJECT
FROM STEVE BY MARY
---
REVOKE DBADM ON SYSTEM
FROM ROLE ADMINROLE
NOT INCLUDING DEPENDENT PRIVILEGES
---
REVOKE DBADM, DATAACCESS, ACCESSCTRL ON SYSTEM
FROM ROLE ADMINROLE
NOT INCLUDING DEPENDENT PRIVILEGES
---
REVOKE SELECT ON TABLE DSN8C10.EMP FROM PULASKI
---
REVOKE UPDATE ON TABLE DSN8C10.EMP FROM PUBLIC
---
REVOKE ALL ON TABLE DSN8C10.EMP FROM KWAN,THOMPSON
---
REVOKE SELECT, UPDATE ON TABLE DSN8C10.DEPT
FROM PUBLIC
---
REVOKE ALTER ON TABLE DSN8C10.EMP
FROM ROLE ROLE1
---
REVOKE USAGE ON TYPE SHOESIZE FROM JONES
---
REVOKE USAGE ON TYPE US_DOLLAR FROM PUBLIC
---
REVOKE USAGE ON TYPE CANADIAN_DOLLARS
 FROM ADMIN_A
---
REVOKE USAGE ON TYPE MILES
 FROM ROLE ROLE1
---
REVOKE USE OF BUFFERPOOL BP2
 FROM MARINO
---
REVOKE USE OF TABLESPACE DSN8D12A.DSN8S12D
 FROM PUBLIC
---
REVOKE USE OF STOGROUP SG1
FROM ROLE ROLE1
---
SET CONNECTION TOROLAB1
---
SET :HVL = CURRENT PATH
---
 SET :SERVER = CURRENT PATH,
:XTIME = CURRENT TIME,
:MEM = CURRENT MEMBER
---
SET :DETAILS = SUBSTR(:LOCATOR,1,35)
---
SELECT SUBSTR(:LOCATOR,1,35)
 INTO :DETAILS
 FROM SYSIBM.SYSDUMMYU
---
SET (SALARY, COMMISSION) = (50000, 8000)
---
SET CURRENT ACCELERATOR = ACCEL1
---
SET CURRENT APPLICATION COMPATIBILITY = "V11R1";
SET CURRENT APPLICATION COMPATIBILITY = :HV1
---
SET CURRENT APPLICATION ENCODING SCHEME = "EBCDIC";
SET CURRENT ENCODING SCHEME  = :HV1
---
SET CURRENT DEBUG MODE = ALLOW
---
SET CURRENT DECFLOAT ROUNDING MODE = ROUND_CEILING
---
SET CURRENT DEGREE = "1"
---
SET CURRENT DEGREE = "ANY"
---
SET CURRENT EXPLAIN MODE = YES
---
SET CURRENT GET_ACCEL_ARCHIVE=NO
---
SET CURRENT LOCALE LC_CTYPE = "En_US"
---
SET CURRENT LOCALE LC_CTYPE = :HV1
---
SET CURRENT MAINTAINED TABLE TYPES ALL
---
VALUES (CURRENT MAINTAINED TABLE TYPES) INTO :CURMAINTYPES
---
SET CURRENT MAINTAINED TABLE TYPES NONE
---
SET CURRENT OPTIMIZATION HINT = "NOHYB"
---
SET CURRENT OPTIMIZATION HINT = ""
---
SET CURRENT PACKAGE PATH :hvar1
---
SET CURRENT PACKAGE PATH =
"COLL1","COLL#2","COLL3", :hvar1
---
SET CURRENT PACKAGE PATH = ' '
---
SET CURRENT PACKAGESET = "PERSONNEL"
---
SET CURRENT PACKAGESET = ""
---
SET CURRENT PRECISION = "DEC15"
---
SET CURRENT QUERY ACCELERATION NONE
---
SET CURRENT QUERY ACCELERATION WAITFORDATA = 180.0
---
SET CURRENT QUERY ACCELERATION WAITFORDATA = 2.5
---
SET CURRENT REFRESH AGE ANY
---
SET CURRENT ROUTINE VERSION = :rvid
---
SET CURRENT RULES = "DB2"
---
SET CURRENT SQLID = SESSION_USER
---
SET CURRENT TEMPORAL BUSINESS_TIME =
       TIMESTAMP('2008-01-01') + 5 DAYS ;
SET CURRENT TEMPORAL BUSINESS_TIME =
      '2008-01-06-00.00.00.000000000000'
---
SET CURRENT TEMPORAL BUSINESS_TIME =
            CURRENT TIMESTAMP - 1 MONTH
UPDATE att1 SET c1 = 5 WHERE pk = 100
---
SET CURRENT TEMPORAL BUSINESS_TIME = NULL
---
SET ENCRYPTION PASSWORD = :hv1
---
SET ENCRYPTION PASSWORD = 'somepwd' WITH HINT :hv2
---
SET PATH = SCHEMA1,"SCHEMA#2", SYSIBM
---
SET PATH = CURRENT PATH, SMITH, SYSPROC
---
SET SCHEMA RICK
---
SELECT CURRENT SCHEMA INTO :CURSCHEMA
 FROM SYSIBM.SYSDUMMY1
---
SET CURRENT SQLID = "USRT001";
SET CURRENT SCHEMA = "USRT002"
---
SET CURRENT SCHEMA = 'JOHN'
---
SET SESSION TIME ZONE = "-8:00"
---
SET :WS-TIMESTAMP =
             TIMESTAMP('1970-01-01-00.00.00.000000')
       + (:WS-TIMESTAMP / 1000) SECOND
       + (INT(CURRENT TIMEZONE/10000)) HOURS
---
ALLOCATE C1 CURSOR FOR RESULT SET :LOC1
---
CONNECT TO SITE2;
CALL SITE2.MYSCHEMA.P1;
ASSOCIATE LOCATORS (:LOC1, :LOC2)
    WITH PROCEDURE :HV1;
---
BEGIN DECLARE SECTION
---
END DECLARE SECTION
---
SELECT
         A.COL4
        ,CASE (A.COL5)
         WHEN '00' THEN 'OK        '
         WHEN '01' THEN 'OK        '
         WHEN '02' THEN 'KO        '
         WHEN '03' THEN 'KO        '
         WHEN '04' THEN '=BLAH'
         ELSE      'KO        '
         END AS CASETEST
INTO    :WS-VAR1
       ,:WS-VAR2
FROM  TABLEA A,
      TABLEB B
WHERE   A.COL1   = B.COL9
  AND   B.COL2  = :WS-VAR3
  AND   A.COL6     <> 'C'
---
DECLARE C1 CURSOR FOR
SELECT DEPTNO, DEPTNAME, MGRNO
FROM DSN8C10.DEPT
WHERE ADMRDEPT = 'A00';
OPEN C1;
FETCH C1 INTO :DNUM, :DNAME, :MNUM;

CLOSE C1;
---
FETCH NEXT ROWSET FROM TEST INTO :VAR
---
select a from table -- random where stuffss ss sdjsd
---
COMMENT ON TABLE DSN8C10.EMP
 IS "REFLECTS 1ST QTR 81 REORG"
---
COMMENT ON COLUMN DSN8C10.DEPT.DEPTNO
IS "DEPARTMENT ID - UNIQUE"
---
COMMENT ON FUNCTION CHEM.ATOMIC_WEIGHT
IS "TAKES ATOMIC NUMBER AND GIVES ATOMIC WEIGHT"
---
COMMENT ON PROCEDURE BIOLOGY.OSMOSIS
IS "CALCULATIONS THAT MODEL OSMOSIS"
---
COMMENT ON ROLE ROLE1
IS "Role defined for trusted context, ctx1"
---
COMMIT WORK
---
CONNECT TO :LOCNAME USER :USER_AUTHID USING :USER_PASSWORD
---
DELETE FROM EMP WHERE CURRENT OF C1
---
DROP TABLE DSN8C10.DEPT
---
DROP TABLESPACE DSN8D12A.DSN8S12D
---
DROP VIEW DSN8C10.VPROJRE1
---
DROP PACKAGE DSN8CC61.DSN8CC0 VERSION VERSZZZZ
---
DROP PACKAGE DSN8.CC0 VERSION '1994sw3'
---
DROP TYPE DOCUMENT
---
DROP FUNCTION CHEM.ATOMIC_WEIGHT
---
DROP FUNCTION CENTER(INTEGER, FLOAT)
---
DROP SPECIFIC FUNCTION JOHNSON.FOCUS97
---
DROP PROCEDURE BIOLOGY.OSMOSIS
---
DROP TRIGGER BONUS
---
DROP ROLE CTXROLE
---
DROP TRUSTED CONTEXT CTX1
---
DROP PUBLIC ALIAS PUBALIAS1 FOR SEQUENCE
---
BEGIN DECLARE SECTION
---
INCLUDE STUDENT
---
END DECLARE SECTION
---
EXCHANGE DATA BETWEEN TABLE EMPCLONE AND EMPLOYEE
---
BEGIN DECLARE SECTION
---
END DECLARE SECTION
---
WHENEVER SQLERROR GO TO 1000-ABEND-RTN
---
EXECUTE IMMEDIATE :SQL-STMT
---
INSERT INTO DSN8C10.DEPT VALUES('s1val')
---
EXECUTE DEPT_INSERT USING :SS
---
EXPLAIN PLAN SET QUERYNO = 13
FOR SELECT X.ACTNO, X.PROJNO, X.EMPNO, Y.JOB, Y.EDLEVEL
FROM DSN8C10.EMPPROJACT X, DSN8C10.EMP Y
  WHERE X.EMPNO = Y.EMPNO
     AND X.EMPTIME > 0.5
      AND (Y.JOB = 'DESIGNER' OR Y.EDLEVEL >= 12)
  ORDER BY X.ACTNO, X.PROJNO;
---
FREE LOCATOR :LOCRES, :LOCHIST, :LOCPIC
---
GET DIAGNOSTICS :rcount = ROW_COUNT
---
SELECT :INP INTO :A.BBB FROM CACHE
---
HOLD LOCATOR :LOCRES, :LOCHIST, :LOCPIC
---
UPDATE QWE_STATUS
    SET A_B_C  = :QWE.D-E-F
    WHERE TKN_UNIQUE_REFERENCE = :ASD.O-P-R
---
HOLD LOCATOR :LOCRES, :LOCHIST, :LOCPIC
---
HOLD LOCATOR :LOCRES2, :LOCHIST2, :LOCPIC2
---
INCLUDE STRUCT1
---
INCLUDE SQLCA
---
INCLUDE SQLDA
---
INCLUDE STRUCT1
---
INCLUDE STRUCT2
---
INSERT INTO DSN8C10.EMP
 VALUES ('000205','MARY','T','SMITH','D11','2866',
      '1981-08-10','ANALYST',16,'F','1956-05-22',
     16345,500,2300)
---
INSERT INTO SMITH.TEMPEMPL
SELECT *
FROM DSN8C10.EMP
---
INSERT INTO SESSION.TEMPEMPL
SELECT *
 FROM DSN8C10.EMP
 WHERE WORKDEPT='D11'
---
INSERT INTO DSN8C10.EMP_PHOTO_RESUME
(EMPNO, EMP_ROWID)
VALUES (:HV_ENUM, DEFAULT)
---
INSERT INTO DSN8C10.EMP_PHOTO_RESUME
(EMPNO,EMP_ROWID)
 VALUES (:HV_ENUM,DEFAULT)
---
SELECT * INTO :HV_ENUM FROM FINAL TABLE (
INSERT INTO ABC INCLUDE (A SMALLINT,
B SMALLINT) VALUEs (:TAD+1)
)
---
INSERT INTO HOUSE
            ( POLICYNUMBER,
              PROPERTYTYPE,
              BEDROOMS,
              VALUE,
              HOUSENAME,
              HOUSENUMBER,
              POSTCODE          )
     VALUES ( :DB2-POLICYNUM-INT,
              :CA-H-PROPERTY-TYPE,
              :DB2-H-BEDROOMS-SINT,
              :DB2-H-VALUE-INT,
              :CA-H-HOUSE-NAME,
              :CA-H-HOUSE-NUMBER,
              :CA-H-POSTCODE      )
---
insert into all values(1,1)
---
insert into all(all,avg)
select all all as all, avg from all
---
INSERT INTO TABLE1
(
  TBL1_FIELD1
 ,TBL1_TIMESTAMP
)
VALUES
(
  :WS-FIELD1
 ,TIMESTAMP(:WS-TIMESTAMP) +
            (:WS-EXPIRES-IN SECONDS)
)
---
LABEL ON COLUMN DSN8C10.DEPT.DEPTNO
IS "DEPARTMENT NUMBER"
---
LABEL ON DSN8C10.DEPT
(MGRNO IS "EMPLOYEE NUMBER FOR THE MANAGER",
ADMRDEPT IS "ADMINISTERING DEPARTMENT")
---
LOCK TABLE DSN8C10.EMP IN EXCLUSIVE MODE
---
MERGE INTO RECORDS AR
USING (SELECT ACTIVITY, DESCRIPTION FROM ACTIVITIES) AC
ON (AR.ACTIVITY = AC.ACTIVITY)
WHEN MATCHED THEN
UPDATE SET
DESCRIPTION = AC.DESCRIPTION
WHEN NOT MATCHED THEN
INSERT
(ACTIVITY, DESCRIPTION)
VALUES (AC.ACTIVITY, AC.DESCRIPTION)
---
MERGE INTO INVENTORY AS IN
USING (SELECT PARTNO, DESCRIPTION, COUNT FROM SHIPMENT
WHERE SHIPMENT.PARTNO IS NOT NULL) AS SH
ON (IN.PARTNO = SH.PARTNO)
WHEN MATCHED THEN
 UPDATE SET
  DESCRIPTION = SH.DESCRIPTION,
  QUANTITY = IN.QUANTITY + SH.COUNT
WHEN NOT MATCHED THEN
 INSERT
 (PARTNO, DESCRIPTION, QUANTITY)
 VALUES (SH.PARTNO, SH.DESCRIPTION, SH.COUNT)
---
MERGE INTO ACCOUNT AS A
 USING (SELECT ID, SUM(AMOUNT) SUM_AMOUNT FROM TRANSACTION
  GROUP BY ID) AS T
  ON A.ID = T.ID
 WHEN MATCHED THEN
  UPDATE SET
   BALANCE = A.BALANCE + T.SUM_AMOUNT
 WHEN NOT MATCHED THEN
  INSERT
  (ID, BALANCE)
   VALUES (T.ID, T.SUM_AMOUNT)
---
MERGE INTO EMPLOYEE_FILE AS E
 USING (SELECT EMPID, PHONE, OFFICE
  FROM (SELECT EMPID, PHONE, OFFICE,
  ROW_NUMBER() OVER (PARTITION BY EMPID
  ORDER BY TRANSACTION_TIME DESC) RN
  FROM TRANSACTION_LOG) AS NT
  WHERE RN = 1) AS T
  ON E.EMPID = T.EMPID
 WHEN MATCHED THEN
  UPDATE SET
   (PHONE, OFFICE) =
   (T.PHONE, T.OFFICE)
 WHEN NOT MATCHED THEN
  INSERT
  (EMPID, PHONE, OFFICE)
  VALUES (T.EMPID, T.PHONE, T.OFFICE)
---
MERGE INTO RECORDS AR
 USING (SELECT ACTIVITY, DESCRIPTION, DATE, LAST_MODIFIED
  FROM ACTIVITIES_GROUPA) AC
  ON (AR.ACTIVITY = AC.ACTIVITY) AND AR.GROUP = 'A'
 WHEN MATCHED AND AC.DATE IS NULL THEN
  SIGNAL SQLSTATE '70001'
   SET MESSAGE_TEXT =
    AC.ACTIVITY CONCAT
    ' CANNOT BE MODIFIED. REASON: DATE IS NOT KNOWN'
 WHEN MATCHED AND AC.DATE < CURRENT DATE THEN
  DELETE
 WHEN MATCHED AND AR.LAST_MODIFIED < AC.LAST_MODIFIED THEN
  UPDATE SET
  (DESCRIPTION, DATE, LAST_MODIFIED) =
  (AC.DESCRIPTION, AC.DATE, DEFAULT)
 WHEN NOT MATCHED AND AC.DATE IS NULL THEN
  SIGNAL SQLSTATE '70002'
   SET MESSAGE_TEXT =
    AC.ACTIVITY CONCAT
   ' CANNOT BE INSERTED. REASON: DATE IS NOT KNOWN'
 WHEN NOT MATCHED AND AC.DATE >= CURRENT DATE THEN
  INSERT
   (GROUP, ACTIVITY, DESCRIPTION, DATE)
   VALUES ('A', AC.ACTIVITY, AC.DESCRIPTION, AC.DATE)
 ELSE IGNORE
---
MERGE INTO RECORDS AR
  USING (VALUES (:hv_activity, :hv_description)
    FOR :hv_nrows ROWS)
    AS AC (ACTIVITY, DESCRIPTION)
  ON (AR.ACTIVITY = AC.ACTIVITY)
  WHEN MATCHED THEN UPDATE SET DESCRIPTION = AC.DESCRIPTION
  WHEN NOT MATCHED THEN INSERT (ACTIVITY, DESCRIPTION)
     VALUES (AC.ACTIVITY, AC.DESCRIPTION)
  NOT ATOMIC CONTINUE ON SQLEXCEPTION
---
MERGE INTO ACCOUNT AS A
  USING (VALUES (:hv_id, :hv_amount)
    FOR 3 ROWS)
    AS T (ID, AMOUNT)
  ON (A.ID = T.ID)
  WHEN MATCHED THEN UPDATE SET BALANCE =
  A.BALANCE + T.AMOUNT
  WHEN NOT MATCHED THEN INSERT (ID, BALANCE)
      VALUES (T.ID, T.AMOUNT)
  NOT ATOMIC CONTINUE ON SQLEXCEPTION
---
SELECT FÖ1R
INTO :ARB-HELLO
FROM 你好
WHERE AD.FÖLR = :ARB-HELLO
          and AD.XYZ = 'hello'
          and AD.OIY =  :ARB-MD
          and привет = hello_halo
          and сайнуу = 'asa'
          and नमस = 'नमस्ते'
WITH UR
---
DECLARE C1 CURSOR FOR
SELECT DEPTNO, DEPTNAME, MGRNO FROM DSN8C10.DEPT
WHERE ADMRDEPT = 'A00';

OPEN C1;
FETCH C1 INTO :DNUM, :DNAME, :MNUM;
CLOSE C1;
---
PREPARE sample FROM :SQL-STMT
---
REFRESH TABLE SALESCOUNT
---
REFRESH TABLE SALESCOUNT QUERYNO 23
---
RELEASE TOROLAB1
---
RELEASE CURRENT
---
RELEASE SAVEPOINT A
---
RENAME TABLE EMP TO EMPLOYEE
---
RENAME TABLE EMP_USA_HIS2002 TO EMPLOYEE_UNITEDSTATES_HISTORY2002
---
RENAME INDEX COMPANY.EMPINDX1 TO EMPLOYEE_INDEX
---
ROLLBACK WORK
---
ROLLBACK WORK TO SAVEPOINT A
---
SAVEPOINT A ON ROLLBACK RETAIN CURSORS
---
SAVEPOINT B UNIQUE ON ROLLBACK RETAIN CURSORS
---
SAVEPOINT A UNIQUE ON ROLLBACK RETAIN CURSORS
---
SELECT MAX(SALARY)
  INTO :MAXSALRY
  FROM DSN8C10.EMP
---
SELECT * INTO :EMPREC
 FROM DSN8C10.EMP
 WHERE EMPNO = '528671'
---
SELECT * INTO :EMPREC
 FROM DSN8C10.EMP
 WHERE EMPNO = '528671'
 WITH RS USE AND KEEP EXCLUSIVE LOCKS
---
SELECT INTCOL1 INTO
 MYINTARRAY1[INTCOL2+:MYINTVAR+1]
 FROM T1
 WHERE INTCOL1 = MYINTARRAY1[INTCOL2]
---
SELECT * FROM DSN8C10.EMP
---
SELECT * FROM DSN8C10.EMP
  ORDER BY HIREDATE
---
SELECT WORKDEPT, AVG(SALARY)
 FROM DSN8C10.EMP
 GROUP BY WORKDEPT
 ORDER BY 2
---
DECLARE UP_CUR CURSOR FOR
SELECT WORKDEPT, EMPNO, SALARY, BONUS, COMM
  FROM DSN8C10.EMP
  WHERE WORKDEPT IN ('D11','D21')
---
SELECT MAX(BONUS), MIN(BONUS), AVG(BONUS)
   INTO :MAX1, :MIN1, :AVG1
   FROM DSN8C10.EMP
   WITH UR
   QUERYNO 13
---
DECLARE C1 CURSOR FOR
 SELECT * FROM RMTTAB
   FETCH FIRST 50 ROWS ONLY
---
SELECT CONCAT('IBM','MAINFRAMER')
 AS Result FROM SYSIBM.SYSDUMMY1
---
select all all, avg from all
---
select all, avg from all
---
select all all as all, avg from all
---
SELECT C_INTRN_SCP_ET
  INTO :A610-C-INTRN-SCP-ET
  FROM VVA610
 WHERE C_ET_SICO     = :A610-C-ET-SICO
 FETCH FIRST 1 ROW ONLY
---
SELECT
  DATE(
  YEAR(DATE(:WS-D-TRANSIT-2B)-1 MONTH)!!
  '-'!!
  MONTH(DATE(:WS-D-TRANSIT-2B)-1 MONTH)!!
  '-'!!
  '01'
  )
INTO :WS-D-DEB
FROM SYSIBM.SYSDUMMY1
---
SELECT
  DATE(
  DAYS(
  DATE(
  YEAR(:WS-D-TRANSIT-2)!!
  '-'!!
  MONTH(:WS-D-TRANSIT-2)!!
  '-'!!
  '01'
  )
  )
  -1)
INTO :WS-D-DEB
FROM SYSIBM.SYSDUMMY1
---
DECLARE C1 CURSOR FOR
 SELECT * FROM RMTTAB
   FOR FETCH ONLY
---
 WITH T1 AS
 (
 SELECT  CARD           AS PAN
        ,CVV            AS CVV2
        ,Y1             AS W1
        ,Y2             AS W2
 FROM TABLEY
 )
 SELECT  'Y'
 INTO   :WS-D-DEB
 FROM TABLEY
 INNER JOIN T1 ON
          TABLEY.Y1         = T1.W1
     AND  TABLEY.Y2         = T1.W2
 WHERE 1 = 1
FETCH FIRST 1 ROW ONLY
WITH UR
---
DECLARE C1 CURSOR FOR
 SELECT * FROM RMTTAB
   LIMIT 1
---
DECLARE C1 CURSOR FOR
 SELECT * FROM RMTTAB
   LIMIT 1,1
---
DECLARE C1 CURSOR FOR
 SELECT * FROM RMTTAB
   LIMIT 1 OFFSET 1
---
DECLARE SYSTAB_CSR CURSOR FOR
    SELECT DISTINCT T.NAME
    FROM SYSIBM.SYSTABLES T
        WHERE T.NAME = 'SYSPLAN'
           AND T.NAME IN
                (SELECT DISTINCT C.TBNAME
                   FROM SYSIBM.SYSCOLUMNS C
                  WHERE C.COLNO IN (1, 2, 3, 4, 5)
                    AND C.COLTYPE = 'CHAR'
                )
          FOR FETCH ONLY
        WITH UR
---
DECLARE SYSTAB_CSR2 CURSOR FOR
        SELECT DISTINCT T.NAME
          FROM SYSIBM.SYSTABLES T
          WHERE T.NAME NOT IN
                (SELECT TB2.TBNAME
                   FROM SYSIBM.SYSCOLUMNS TB2
                  WHERE TB2.NAME = 'NAME'
                )
          FOR FETCH ONLY
        WITH UR
---
SIGNAL SQLSTATE '75002'
SET MESSAGE_TEXT = 'Customer number is not known'
---
DECLARE CUR-550 CURSOR FOR
    SELECT C_ISIN
    FROM   VVA550
    WHERE  D_EFF_DEB >= :WS-F900-JOUR-TRAIT
    UNION
    SELECT C_ISIN
    FROM   VVA550
    WHERE  D_EFF_FIN >= :WS-F900-JOUR-TRAIT
    FOR FETCH ONLY
---
EXCHANGE DATA BETWEEN TABLE EMPCLONE AND 'EMPCLONE£'
---
TRANSFER OWNERSHIP OF DATABASE DBCC001 TO USER USRT001
REVOKE PRIVILEGES
---
TRANSFER OWNERSHIP OF DATABASE DBCC002 TO ROLE OWNRROLE
REVOKE PRIVILEGES
---
TRANSFER OWNERSHIP OF DATABASE DBCC003 TO SESSION_USER
REVOKE PRIVILEGES
---
TRANSFER OWNERSHIP OF TABLE EMPLOYEE.DEPT TO ROLE TBOWNR_ROLE
REVOKE PRIVILEGES
---
TRANSFER OWNERSHIP OF INDEX EMPLOYEE.SALARYIX TO USER IXOWNER
REVOKE PRIVILEGES
---
TRUNCATE TABLE INVENTORY
DROP STORAGE
IGNORE DELETE TRIGGERS
---
TRUNCATE TABLE INVENTORY
REUSE STORAGE
IGNORE DELETE TRIGGERS
---
TRUNCATE TABLE INVENTORY
REUSE STORAGE
IGNORE DELETE TRIGGERS
IMMEDIATE
---
UPDATE DSN8C10.EMP
 SET PHONENO='3565'
 WHERE EMPNO='000190'
---
UPDATE DSN8C10.EMP
 SET SALARY = SALARY + 100
 WHERE WORKDEPT = 'D11';
---
UPDATE DSN8C10.EMP
 SET SALARY = NULL, BONUS = NULL, COMM = NULL
 WHERE EMPNO='000250';
---
UPDATE DSN8C10.EMP
 SET PROJSIZE = (SELECT COUNT(*)
  FROM DSN8C10.PROJ
  WHERE DEPTNO = 'E21')
WHERE WORKDEPT = 'E21';
---
UPDATE DSN8C10.EMP
  SET SALARY = 2 * SALARY
 WHERE CURRENT OF C1;
---
UPDATE EMP1
 SET SALARY = SALARY + 1000,
  RESUME = UPDATE_RESUME(:HV_RESUME)
  WHERE EMP_ROWID = :HV_EMP_ROWID;
---
UPDATE EMP X
 SET SALARY = 1.10 * SALARY
 WHERE SALARY < (SELECT AVG(SALARY) FROM EMP Y
 WHERE X.JOBCODE = Y.JOBCODE);
---
UPDATE EMP T1
 SET SALARY = (SELECT AVG(T2.SALARY) FROM EMP T2)
 WHERE WORKDEPT = 'E11' AND
 SALARY < (SELECT AVG(T3.SALARY) FROM EMP T3);
---
UPDATE DSN8710.EMP
  SET BONUS = ( SELECT .10 * SALARY FROM DSN8710.EMP Y
  WHERE EMPNO = Y.EMPNO )
WHERE CURRENT OF C1;
---
UPDATE T1 SET C1 = 5 WHERE CURRENT OF CS1;
---
VALUES(CURRENT PATH) INTO :HV1
---
VALUES(CURRENT MEMBER) INTO :MEM
---
VALUES (SUBSTR(:LOB1,1,35)) INTO :DETAILS
---
VALUES INTVAR1 INTO MYINTARRAY1[23]
---
CREATE TRIGGER EMPISRT1
AFTER INSERT ON EMP
REFERENCING NEW AS N
FOR EACH ROW
BEGIN ATOMIC
 VALUES(NEWEMP(N.EMPNO, N.LASTNAME,N.FIRSTNAME));
END
---
WHENEVER SQLERROR GOTO HANDLER
---
WHENEVER SQLWARNING CONTINUE
---
WHENEVER NOT FOUND GO TO ENDDATA
---
ALTER PROCEDURE NAME1 SECURITY DB2
---
SET CURRENT QUERY ACCELERATION WAITFORDATA 10
---
ALTER SPECIFIC FUNCTION func RESTRICT DETERMINISTIC
---
ALTER INDEX X1
BUFFERPOOL BP1
ALTER PARTITION 3
DSSIZE 1g
FREEPAGE 4
PCTFREE 1
GBPCACHE NONE
---
ALTER INDEX X1 REGENERATE USING APPLICATION COMPATIBILITY V12R1M500
---
ALTER PROCEDURE pname1
GET_ACCEL_ARCHIVE YES
ACCELERATION WAITFORDATA 1234.0
---
COMMENT ON TRUSTED CONTEXT CTX1 
IS 'WEBSPHERE SERVER'
---
CREATE TABLE TBL (
  id INT NOT NULL GENERATED AS IDENTITY(NO MAXVALUE)
);
---
CREATE TRIGGER REORDER
AFTER UPDATE OF ON_HAND, MAX_STOCKED ON PARTS
REFERENCING NEW AS NROW
FOR EACH ROW
WHEN (NROW.ON_HAND < 0.10 * NROW.MAX_STOCKED)
BEGIN ATOMIC
   VALUES(NEWEMP(N.EMPNO, N.LASTNAME,N.FIRSTNAME));
END;
---
DECLARE C1 CURSOR WITH HOLD WITH RETURN FOR
SELECT column1, column2
FROM my_table
WHERE condition = 1;
---
EXECUTE IMMEDIATE --IMMEDIATE in the role of an identifier!
---
EXPLAIN PACKAGE COLLECTION 'COLLA'
PACKAGE 'PACKA' COPY 'CURRENT'
---
EXPLAIN STABILIZED DYNAMIC QUERY STMTID 1 COPY 'CURRENT'
---
FETCH SENSITIVE WITH CONTINUE
next --next in the role of the cursor name!
INTO DESCRIPTOR :COMA;
---
GRANT CREATEDBC ON SYSTEM TO SALLY;
---
GRANT UPDATE (EMPNO, WORKDEPT)
ON TABLE DSN8C10.EMP TO PUBLIC
---
GRANT USAGE ON JAR DEVL7083.EmpJar, SecondThing TO PAOLO
---
PREPARE DEPT_INSERT FROM "DROP TABLE dept";
---
REVOKE CREATEDBC ON SYSTEM FROM SALLY;
---
REVOKE UNLOAD ON SYSTEM FROM SALLY;
---
REVOKE USAGE ON JAR COMMON.MathFunctionsJar FROM PUBLIC BY DBADM;
---
REVOKE READ ON VARIABLE accountNo FROM JONES;
---
REVOKE WRITE ON VARIABLE us_dollar FROM PUBLIC;
---
REVOKE ALL PRIVILEGES ON VARIABLE v1 FROM ROLE role1;
---
SET array_variable[1] = 100;
---
SET array_variable[:HOST] = 100;
---
SET CURRENT OPTIMIZATION HINT = :AREA;
---
SET CURRENT DEGREE = :AREA;
---
SET SESSION TIMEZONE = "UTC";
---
SET SESSION TIME ZONE = "UTC";
