import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { PlOneGeneratedModule, PlOneGeneratedSharedModule } from './generated/module.js';
import { PlOneValidator, registerValidationChecks } from './pl-one-validator.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type PlOneAddedServices = {
    validation: {
        PlOneValidator: PlOneValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type PlOneServices = LangiumServices & PlOneAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const PlOneModule: Module<PlOneServices, PartialLangiumServices & PlOneAddedServices> = {
    validation: {
        PlOneValidator: () => new PlOneValidator()
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createPlOneServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    PlOne: PlOneServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        PlOneGeneratedSharedModule
    );
    const PlOne = inject(
        createDefaultModule({ shared }),
        PlOneGeneratedModule,
        PlOneModule
    );
    shared.ServiceRegistry.register(PlOne);
    registerValidationChecks(PlOne);
    return { shared, PlOne };
}
