#!/usr/bin/env npx tsx
/**
 * This program and the accompanying materials are made available under the terms of the
 * Eclipse Public License v2.0 which accompanies this distribution, and is available at
 * https://www.eclipse.org/legal/epl-v20.html
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Copyright Contributors to the Zowe Project.
 *
 */

import { readFile, writeFile } from "fs/promises";

// These keywords are used by CICS and PLI at the same time.
// PLI has precedence over CICS. Extend the list when getting into import trouble in tokens.ts
const blacklist = new Set([
  "ALLOCATE",
  "AND",
  "AS",
  "ATTACH",
  "BINARY",
  "BIT",
  "CANCEL",
  "CHAR",
  "CLOSE",
  "CONDITION",
  "COPY",
  "DATA",
  "DATE",
  "DEFAULT",
  "DEFINE",
  "DELAY",
  "DELETE",
  "END",
  "ENDFILE",
  "ENTRY",
  "ERROR",
  "EVENT",
  "EXTERNAL",
  "FETCH",
  "FILE",
  "FREE",
  "FROM",
  "GENERIC",
  "GET",
  "HANDLE",
  "IGNORE",
  "INPUT",
  "INTO",
  "LABEL",
  "LINE",
  "LIST",
  "MAIN",
  "NAME",
  "NOTE",
  "ON",
  "OPEN",
  "OPTIONS",
  "OR",
  "ORGANIZATION",
  "OUTPUT",
  "PAGE",
  "PASSWORD",
  "POP",
  "PRINT",
  "PROCESS",
  "PUSH",
  "PUT",
  "READ",
  "RECORD",
  "RELEASE",
  "REPLACE",
  "REPLY",
  "RETCODE",
  "RETURN",
  "REWRITE",
  "SET",
  "SIGNAL",
  "STORAGE",
  "TASK",
  "TEXT",
  "TITLE",
  "TO",
  "TYPE",
  "UNTIL",
  "UPDATE",
  "VALUE",
  "WAIT",
  "WRITE",
]);

const licenseHeader = await readFile("./license-header.js", "utf8");

type CicsKeywordFile = {
  control: string[];
  storage: string[];
};

const cicsKeywords = JSON.parse(
  await readFile(
    "./packages/vscode-extension/syntaxes/cics-keywords.json",
    "utf8",
  ),
) as CicsKeywordFile;

const control = new Set(cicsKeywords.control);

let sourceCode = `${licenseHeader}
// THIS FILE WAS GENERATED BY scripts/generate-cics-keyword-tokens.mts
// DO NOT EDIT THIS FILE DIRECTLY. INSTEAD, EDIT THE GENERATOR AND RE-GENERATE THE FILE.

import { registerKeyword, KeywordType } from "./shared";

`;

for (const element of cicsKeywords.control
  .concat(cicsKeywords.storage)
  .sort()) {
  if (blacklist.has(element)) {
    continue;
  }
  const keyword = element.toUpperCase();
  sourceCode += `export const ${keyword} = registerKeyword({
  name: "${keyword}",${control.has(element) ? "\n  type: KeywordType.Control," : ""}
});
`;
}

await writeFile(
  "./packages/language/src/parser/tokens/cics-tokens.generated.ts",
  sourceCode,
);
