name: Build

on: [push, workflow_dispatch]

jobs:
  build-intellij:
    runs-on: ubuntu-latest
    # Changing WORKING_DIRECTORY, don't forget to change defaults.run.working-directory
    env:
      WORKING_DIRECTORY: intellij-plugin
    defaults:
      run:
        working-directory: ./intellij-plugin
    steps:

      - name: Checkout the plugin GitHub repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Check repository content
        shell: bash
        run: pwd && ls -la

      - name: Test plugin
        shell: bash
        run: ./gradlew test

      - name: Build plugin
        shell: bash
        run: ./gradlew buildPlugin

      - name: Prepare Plugin Artifact
        id: artifact
        shell: bash
        run: |
          cd ${{ github.workspace }}/${{ env.WORKING_DIRECTORY }}/build/distributions
          FILENAME=`ls *.zip`
          unzip "$FILENAME" -d content
          echo "filename=${FILENAME:0:-4}" >> $GITHUB_OUTPUT
          echo "zip artifact name:"
          echo "$FILENAME"

      - name: Publish built plugin to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.filename }}
          path: ./${{ env.WORKING_DIRECTORY }}/build/distributions/content/*/*
