name: Deploy PR preview

permissions:
  pages: write
  id-token: write
  contents: write

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Actually checkout the PR branch
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install pnpm
        if: github.event.action != 'closed'
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js
        if: github.event.action != 'closed'
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Build PR Preview
        if: github.event.action != 'closed'
        run: |
          pnpm install --frozen-lockfile
          pnpm build
          pnpm playground
      - uses: rossjrw/pr-preview-action@v1.6.0
        with:
          source-dir: ./packages/playground/out
          preview-branch: previews
          umbrella-dir: pr
          token: ${{ secrets.PREVIEW_PAT_TOKEN }}
